src/OpenSage.Game/Data/Ini/Parser/IniParser.cs
=> Use ParseUtility.ParseFloat for ini floats

NuGet.config, src/OpenSage.DataViewer.Windows/OpenSage.DataViewer.Windows.csproj, src/OpenSage.DataViewer/UI/ContentView.cs, src/OpenSage.DataViewer/UI/Viewers/WavView.cs, src/OpenSage.Game/Audio/AudioBuffer.cs, src/OpenSage.Game/Audio/AudioSource.cs, src/OpenSage.Game/Audio/AudioSystem.cs, src/OpenSage.Game/Content/ContentManager.cs, src/OpenSage.Game/Content/WavLoader.cs, src/OpenSage.Game/Data/Wav/WavFile.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/OpenSage.Game.csproj
- adds .wav loading
- add a .wav viewer that does playback the sound in a loop
still WIP (sounds don't stop when switching the view)
=> Work on an audiosystem

src/OpenSage.DataViewer/Framework/InstallationUtility.cs, src/OpenSage.Game/Data/InstallationLocator.cs, src/OpenSage.Game/IGameDefinition.cs, src/OpenSage.Mods.Bfme/BfmeDefinition.cs, src/OpenSage.Mods.Bfme2/Bfme2Definition.cs, src/OpenSage.Mods.Bfme2/Bfme2RotwkDefinition.cs, src/OpenSage.Mods.Cnc3/Cnc3Definition.cs, src/OpenSage.Mods.Cnc3/Cnc3KanesWrathDefinition.cs, src/OpenSage.Mods.Cnc4/Cnc4Definition.cs, src/OpenSage.Mods.Generals/GeneralsDefinition.cs, src/OpenSage.Mods.Generals/GeneralsZeroHourDefinition.cs, src/OpenSage.Mods.Ra3/Ra3Definition.cs, src/OpenSage.Mods.Ra3/Ra3UprisingDefinition.cs
This PR should implement a second Installation Locator using environment variables, mainly to support none-windows systems.
=> Environment Variable Installation Locator

src/OpenSage.Game/Content/WindowLoader.cs, src/OpenSage.Game/Gui/Wnd/Controls/Window.cs
Fixes mouse camera control when controlbar is visible
=> Fix Wnd window sizing

src/OpenSage.Launcher/Program.cs
I got tired of having to edit `Program.cs` every time I want to test something in-game.
=> Add --map command to launcher to help with debugging

src/OpenSage.Game/Game.cs, src/OpenSage.Game/Logic/Orders/OrderProcessor.cs, src/OpenSage.Mods.Generals/Gui/ReplayMenuCallbacks.cs
This is all very hard-coded, temporary code,  but it should serve as a stepping stone to something better.
=> Add StartingBuilding and StartingUnit0 to game objects

src/OpenSage.DataViewer/UI/ContentView.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/GameFactory.cs, src/OpenSage.Game/GameWindow.cs, src/OpenSage.Launcher/Program.cs
This will allow the imgui-based viewer to create a single `GameWindow` and `GraphicsDevice`, and switch between `Game` instances as needed.
=> Create GraphicsDevice in GameWindow

src/Directory.Build.props, src/OpenSage.Game/Graphics/Effects/Effect.cs, src/OpenSage.Game/OpenSage.Game.csproj
- Updates Veldrid to support native HLSL and Metal compilation
- Added Shaderc wrapper to support GLSL->Vulkan
- Always check first if bytecode already exists
=> Work on online compilation

NuGet.config, src/Directory.Build.props, src/OpenSage.Game/GameWindow.cs, src/OpenSage.Game/OpenSage.Game.csproj, src/OpenSage.Launcher/OpenSage.Launcher.csproj, src/OpenSage.Viewer/OpenSage.Viewer.csproj
=> [WIP] Add trimming support

src/Directory.Build.props, src/OpenSage.Game/Audio/AudioSource.cs, src/OpenSage.Game/Audio/AudioSystem.cs, src/OpenSage.Game/Content/WindowLoader.cs, src/OpenSage.Game/Data/Wav/DviApcmParser.cs, src/OpenSage.Game/Data/Wav/PcmParser.cs, src/OpenSage.Game/Data/Wav/WavFile.cs, src/OpenSage.Game/Gui/Wnd/Controls/Button.cs, src/OpenSage.Game/Gui/Wnd/Controls/Window.cs, src/OpenSage.Viewer/UI/Views/WavView.cs
Plays the correct sound when pressing a Button in Generals. Loads the corresponding settings from the .ini files. Split WavParsers into seperate files.
=> Added GUI sounds

src/OpenSage.Game/Graphics/Effects/EffectParameter.cs, src/OpenSage.Game/Gui/Wnd/Controls/ListBox.cs, src/OpenSage.Game/Gui/Wnd/WndInputMessageHandler.cs, src/OpenSage.Game/Gui/Wnd/WndWindowMessage.cs, src/OpenSage.Game/Gui/Wnd/WndWindowMessageType.cs, src/OpenSage.Mods.Generals/Gui/CreditsMenuCallbacks.cs
=> Handle escape press in credits

src/OpenSage.Viewer/UI/MainForm.cs
I broke this with the ImGui update
=> Open the popup dialog

src/OpenSage.Launcher/Program.cs
Do not close window immediately if no game installation is fount, instead wait for user input.
=> wait for user input if no installation is found

NuGet.config, src/OpenSage.Game/Gui/Apt/ActionScript/InstructionCollection.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Opcodes/Arithmetic.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Opcodes/Basic.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Opcodes/Function.cs, src/OpenSage.Game/OpenSage.Game.csproj
=> Fix apt rendering

src/OpenSage.Game.Tests/Content/LoadMapsTests.cs, src/OpenSage.Game/Content/MapLoader.cs, src/OpenSage.Game/Data/Map/MapObject.cs, src/OpenSage.Game/Data/Map/RoadType.cs
Fixes a lot of maps, including GLA01, USA02 and USA04.
=> Road loading fixes

src/Directory.Build.props
Fixes a bug in AdPcm decompression
=> Update to latest SharpAudio

src/OpenSage.Game/Assets/Shaders/FixedFunction.frag, src/OpenSage.Game/Content/ModelLoader.cs, src/OpenSage.Game/Content/Util/ConversionExtensions.cs, src/OpenSage.Game/Graphics/ModelMesh.cs, src/OpenSage.Game/Graphics/Rendering/Shadows/ShadowConstantsPS.cs, src/OpenSage.Game/Graphics/Shaders/FixedFunction.cs
=> Fix various BFME I w3d issues

src/OpenSage.Game/Content/MapLoader.cs, src/OpenSage.Game/Data/Ini/BridgeTemplate.cs, src/OpenSage.Game/Data/Ini/IniDataContext.cs, src/OpenSage.Game/Data/Ini/Parser/IniParser.cs, src/OpenSage.Game/Graphics/ModelMesh.cs, src/OpenSage.Game/Scene3D.cs, src/OpenSage.Game/Terrain/Bridge.cs, src/OpenSage.Game/Terrain/Road.cs, src/OpenSage.Viewer/UI/Views/Ini/ObjectDefinitionView.cs, src/OpenSage.Viewer/UI/Views/Ini/ParticleSystemView.cs, src/OpenSage.Viewer/UI/Views/MapView.cs, src/OpenSage.Viewer/UI/Views/W3dView.cs
=> Render bridges

src/OpenSage.Game.Tests/Utilities/TriangulatorTests.cs, src/OpenSage.Game/Assets/Shaders/Water.frag, src/OpenSage.Game/Assets/Shaders/Water.vert, src/OpenSage.Game/Content/ContentManager.cs, src/OpenSage.Game/Content/MapLoader.cs, src/OpenSage.Game/Graphics/Effects/EffectLibrary.cs, src/OpenSage.Game/Scene3D.cs, src/OpenSage.Game/Terrain/WaterArea.cs, src/OpenSage.Game/Terrain/WaterMaterial.cs, src/OpenSage.Game/Utilities/Triangulator.cs, src/OpenSage.Viewer/UI/Views/Ini/ObjectDefinitionView.cs, src/OpenSage.Viewer/UI/Views/Ini/ParticleSystemView.cs, src/OpenSage.Viewer/UI/Views/MapView.cs, src/OpenSage.Viewer/UI/Views/W3dView.cs
Still to do:
* Water texure animation
* "Bubble" texture
* Sky texture
* Fade from transparent at surface to opaque
... but it already looks much better than not having water:
=> Implement basic water area rendering

src/OpenSage.Game/Game.cs, src/OpenSage.Game/Gui/Wnd/Controls/Button.cs, src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
* Fix 2D scenes without a 3D scene (e.g wnd preview)
* Fix crash when selecting an object that has no associated command set
* Implement push & hover effects for control bar buttons
=> Controlbar improvements & crash fixes

src/OpenSage.Game/Assets/Shaders/FixedFunction.frag, src/OpenSage.Game/Assets/Shaders/Mesh.h, src/OpenSage.Game/Content/ContentManager.cs, src/OpenSage.Game/Content/MapLoader.cs, src/OpenSage.Game/Content/ModelLoader.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/Graphics/Effects/MeshMaterial.cs, src/OpenSage.Game/Graphics/ModelInstance.cs, src/OpenSage.Game/Graphics/ModelMesh.cs, src/OpenSage.Game/Graphics/Rendering/RenderItem.cs, src/OpenSage.Game/Graphics/Rendering/RenderList.cs, src/OpenSage.Game/Graphics/Rendering/RenderPipeline.cs, src/OpenSage.Game/Logic/Object/Draw/DrawModule.cs, src/OpenSage.Game/Logic/Object/Draw/W3dModelDraw.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/GameObjectCollection.cs, src/OpenSage.Game/Logic/Orders/OrderProcessor.cs, src/OpenSage.Game/Logic/Player.cs, src/OpenSage.Game/Mathematics/ColorRgb.cs, src/OpenSage.Viewer/UI/Views/Ini/ObjectDefinitionView.cs, src/OpenSage.Viewer/UI/Views/W3dView.cs
=> Apply house colour to meshes

src/OpenSage.Game/Gui/Apt/ActionScript/InstructionCollection.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Opcodes/Arithmetic.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Opcodes/Function.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Opcodes/Logic.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Opcodes/Stack.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Value.cs
Which are `EA_PushRegister`, `EA_PushConstantWord`, `EA_CallFuncPop`, `StrictEqual`.
=> Implemented few more instructions for Apt

src/OpenSage.Game/Logic/Object/Draw/W3dModelDraw.cs
Prevents crashes when not FXParticleSystem are available
=> Fix crash for particle system bones

src/OpenSage.Game/Content/SubsystemLoader.cs, src/OpenSage.Game/Content/TranslationManager.cs, src/OpenSage.Game/Content/WindowLoader.cs, src/OpenSage.Game/Data/Ini/MapCache.cs, src/OpenSage.Game/Data/Ini/Parser/IniParser.cs, src/OpenSage.Game/Gui/Wnd/Controls/ListBox.cs, src/OpenSage.Game/Gui/Wnd/Controls/RadioButton.cs, src/OpenSage.Game/Gui/Wnd/Images/WndImageLoader.cs, src/OpenSage.Mods.Generals/Gui/MainMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/MapUtils.cs, src/OpenSage.Mods.Generals/Gui/MessageBoxCallbacks.cs, src/OpenSage.Mods.Generals/Gui/SkirmishGameOptionsMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/SkirmishMapSelectMenuCallbacks.cs, src/OpenSage.Viewer/UI/Views/CsfView.cs
Enables the Map selection in SkirmishGameOptions
=> Map selection

src/OpenSage.Game/Content/MapLoader.cs
Fixes training01.map (and potentially some other maps)
=> Fix crash when no team is found

src/OpenSage.Game/Content/TranslationManager.cs, src/OpenSage.Game/Content/WindowLoader.cs, src/OpenSage.Game/Gui/Wnd/Controls/ComboBox.cs, src/OpenSage.Game/Gui/Wnd/Controls/ListBox.cs, src/OpenSage.Game/Gui/Wnd/WndCallbackResolver.cs, src/OpenSage.Mods.Generals/Gui/GameOptionsUtil.cs, src/OpenSage.Mods.Generals/Gui/LanGameOptionsMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/LanLobbyMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/LanMapSelectMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/MainMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/NetworkDirectConnectCallbacks.cs, src/OpenSage.Mods.Generals/Gui/SkirmishGameOptionsMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/SkirmishMapSelectMenuCallbacks.cs
Also fixes some minor issues with the wnd callback system and ListBox
=> Work on LAN gui

src/OpenSage.Game.Tests/Content/LoadMapsTests.cs, src/OpenSage.Game.Tests/Data/InstalledFilesTestData.cs, src/OpenSage.Game/Content/TranslationManager.cs, src/OpenSage.Game/Data/FileSystem.cs, src/OpenSage.Game/Data/Ini/MapCache.cs, src/OpenSage.Game/Diagnostics/GameView.cs, src/OpenSage.Game/Diagnostics/MainView.cs, src/OpenSage.Game/Gui/Wnd/Controls/ListBox.cs, src/OpenSage.Mods.Generals/Gui/GameOptionsUtil.cs, src/OpenSage.Mods.Generals/Gui/LanMapSelectMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/SkirmishGameOptionsMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/SkirmishMapSelectMenuCallbacks.cs
Fixes the map names in ZH and prevents crashes related to different mapcache
=> Fix crashes in C&C ZH

src/OpenSage.Game/Content/ContentManager.cs, src/OpenSage.Game/Content/Translation/ITranslationManager.cs, src/OpenSage.Game/Content/Translation/ITranslationProvider.cs, src/OpenSage.Game/Content/Translation/Providers/CsfTranslationProvider.cs, src/OpenSage.Game/Content/Translation/TranslationManager.cs, src/OpenSage.Game/Content/Translation/TranslationProvider.cs, src/OpenSage.Game/Content/Translation/TranslationProviderBase.cs, src/OpenSage.Game/Content/WindowLoader.cs, src/OpenSage.Game/Data/FileSystemEntry.cs, src/OpenSage.Game/Diagnostics/MainView.cs, src/OpenSage.Game/Diagnostics/StringsView.cs, src/OpenSage.Game/DisplayAttribute.cs, src/OpenSage.Game/Gui/Apt/RenderItem.cs, src/OpenSage.Game/Gui/TextCache.cs, src/OpenSage.Game/Logic/Player.cs, src/OpenSage.Game/Utilities/Extensions/EnumExtensions.cs, src/OpenSage.Mods.Generals/Gui/CreditsMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/GameOptionsUtil.cs, src/OpenSage.Mods.Generals/Gui/LanMapSelectMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/MainMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/SkirmishMapSelectMenuCallbacks.cs
Adds a new Translation Manager with the ability to register multiple providers.
Adds the ability to respond to a language change.
=> Translation stuff

src/OpenSage.Game/Diagnostics/LuaScriptConsole.cs, src/OpenSage.Game/Diagnostics/MainView.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/OpenSage.Game.csproj, src/OpenSage.Game/Scripting/Lua/LuaCompability.cs, src/OpenSage.Game/Scripting/LuaScriptEngine.cs
- integrated lua 5.2 based on moonsharp
- lua script console
- SAGE lua 4.0.1 compatibility code
- auto load of data/scripts/scripts.lua (from big or folder)
- some SAGE specific lua functions already implemented
=> lua-script-engine

src/OpenSage.Game/Data/Apt/Characters/Button.cs, src/OpenSage.Game/Gui/Apt/ActionScript/InstructionCollection.cs
`ButtonRecord`'s `color` seems like to be a `ColorRgbaF` rather than `ColorRgba`;
Also fixed the wrong instruction in `InstructionCollection.cs`
=> Fixed some bugs in apt's code

src/Directory.Build.props, src/OpenSage.Game.Tests/Content/LoadMapsTests.cs, src/OpenSage.Game.Tests/Data/InstalledFilesTestData.cs, src/OpenSage.Game.Tests/OpenSage.Game.Tests.csproj, src/OpenSage.Game/Configuration.cs, src/OpenSage.Game/Content/MapLoader.cs, src/OpenSage.Game/Diagnostics/MainView.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/GameWindow.cs, src/OpenSage.Game/OpenSage.Game.csproj, src/OpenSage.Launcher/Program.cs
This somewhat fixes #126 , but there are still issues with fliiping and missing textures
=> [WIP] Update veldrid and some other dependencies

src/OpenSage.Game/Content/SubsystemLoader.cs, src/OpenSage.Game/Data/Ini/IniDataContext.cs, src/OpenSage.Game/Data/Ini/Parser/IniParser.cs, src/OpenSage.Game/Logic/Object/Draw/W3dModelDraw.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/OrderGeneratorInputHandler.cs, src/OpenSage.Game/Logic/OrderGeneratorSystem.cs, src/OpenSage.Game/Logic/OrderGenerators/TrainUnitOrderGenerator.cs, src/OpenSage.Game/Logic/Orders/Order.cs, src/OpenSage.Game/Logic/Orders/OrderProcessor.cs, src/OpenSage.Game/Logic/Player.cs, src/OpenSage.Game/Logic/SelectionMessageHandler.cs, src/OpenSage.Game/Logic/SelectionSystem.cs, src/OpenSage.Game/Scene3D.cs, src/OpenSage.Game/Terrain/Bridge.cs, src/OpenSage.Game/Terrain/HeightMap.cs, src/OpenSage.Game/Transform.cs, src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
This adds initial movement and construction behaviour
=> Movement and construction

CONTRIBUTING.md, docs/coding-style.md, docs/developer-guide.md
Due to multiple requests by new contributors i started writing down some guidelines & guides, which should help lowering the entry barrier for newcomers. The contribution & style rules are almost the same as in [CoreFX](https://github.com/dotnet/corefx)
=> Add contribution guidelines

src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
=> only show the control bar controls for own units

src/OpenSage.Game/Content/Loaders/OnDemandAnimationLoader.cs, src/OpenSage.Game/Data/Ini/IniParser.cs, src/OpenSage.Game/Logic/Object/AnimationState.cs, src/OpenSage.Game/Logic/Object/Draw/W3dModelDraw.cs
I used for BFME upwards to create more complex animations
=> Add support for animationstates

src/OpenSage.Game/Game.cs, src/OpenSage.Game/Graphics/Cameras/ArcballCameraController.cs, src/OpenSage.Game/Graphics/Cameras/ICameraController.cs, src/OpenSage.Game/Graphics/Cameras/RtsCameraController.cs, src/OpenSage.Game/Logic/Player.cs, src/OpenSage.Game/Scene3D.cs
=> starts the game with the camera on the players starting building

.vscode/launch.json, appveyor.yml, src/OpenSage.Benchmarks.DataStructures/OpenSage.Benchmarks.DataStructures.csproj, src/OpenSage.Core/OpenSage.Core.csproj, src/OpenSage.FileFormats.Big/OpenSage.FileFormats.Big.csproj, src/OpenSage.FileFormats.RefPack/OpenSage.FileFormats.RefPack.csproj, src/OpenSage.FileFormats.W3d/OpenSage.FileFormats.W3d.csproj, src/OpenSage.FileFormats/OpenSage.FileFormats.csproj, src/OpenSage.Game.Tests/OpenSage.Game.Tests.csproj, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/OpenSage.Game.csproj, src/OpenSage.Launcher/OpenSage.Launcher.csproj, src/OpenSage.Mathematics/OpenSage.Mathematics.csproj, src/OpenSage.Mods.Bfme/OpenSage.Mods.Bfme.csproj, src/OpenSage.Mods.Bfme2/OpenSage.Mods.Bfme2.csproj, src/OpenSage.Mods.BuiltIn/OpenSage.Mods.BuiltIn.csproj, src/OpenSage.Mods.Cnc3/OpenSage.Mods.Cnc3.csproj, src/OpenSage.Mods.Cnc4/OpenSage.Mods.Cnc4.csproj, src/OpenSage.Mods.Generals/OpenSage.Mods.Generals.csproj, src/OpenSage.Mods.Ra3/OpenSage.Mods.Ra3.csproj, src/OpenSage.Tools.BigEditor/OpenSage.Tools.BigEditor.csproj
Just switching to the newer runtime by itself already gives great performance boost.
Still figuring out what new APIs are interesting for us and will add it in here.
=> Switch to .NET Core 3

src/OpenSage.Game/Scene3D.cs, src/OpenSage.Game/Scripting/Actions/CameraActions.cs, src/OpenSage.Game/Settings/WorldLighting.cs
Only takes care of the LookAt of the named camera. The Unknowns are probably position & lookup vector?
=> Fix BFME shellmaps

src/OpenSage.Game/Assets/Shaders/Water.frag, src/OpenSage.Game/Content/ScopedAssetCollection.cs, src/OpenSage.Game/Diagnostics/MainView.cs, src/OpenSage.Game/Graphics/Shaders/WaterShaderResources.cs, src/OpenSage.Game/Scene3D.cs, src/OpenSage.Game/Terrain/WaterArea.cs, src/OpenSage.Game/Terrain/WaterAreaCollection.cs
Added support for water & wave areas. Support water bump textures
=> Support BFME water areas

src/OpenSage.Benchmarks.DataStructures/BitArray512CheckExisting.cs, src/OpenSage.Benchmarks.DataStructures/BitArray512SetAllAndCount.cs, src/OpenSage.Benchmarks.DataStructures/BitArray512SetAllExceptOneAndCount.cs, src/OpenSage.Benchmarks.DataStructures/BitArray512SetHalfRandomlyAndCount.cs, src/OpenSage.Benchmarks.DataStructures/OpenSage.Benchmarks.DataStructures.csproj, src/OpenSage.Benchmarks.DataStructures/Program.cs, src/OpenSage.Game.Tests/Mathematics/BitArray512Tests.cs, src/OpenSage.Game/Data/Ini/IniParser.Attributes.cs, src/OpenSage.Game/Data/Ini/IniParser.Enums.cs, src/OpenSage.Game/Diagnostics/AssetViews/GameObjectView.cs, src/OpenSage.Game/Logic/Object/Draw/W3dModelDraw.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Orders/OrderProcessor.cs, src/OpenSage.Game/Scripting/LuaScriptEngine.cs, src/OpenSage.Mathematics/BitArray512.cs, src/OpenSage.Mathematics/BitArray`1.cs
=> Optimize BitArray and fix model condition state selection

src/OpenSage.Game/Data/Apt/Characters/Button.cs, src/OpenSage.Game/Gui/Apt/ActionScript/ActionContext.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Function.cs, src/OpenSage.Game/Gui/Apt/ActionScript/InstructionCollection.cs, src/OpenSage.Game/Gui/Apt/ActionScript/InstructionStream.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Library/Builtin.cs, src/OpenSage.Game/Gui/Apt/ActionScript/ObjectContext.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Opcodes/Basic.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Opcodes/Branch.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Opcodes/Function.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Opcodes/Stack.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Opcodes/Url.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Property.cs, src/OpenSage.Game/Gui/Apt/ActionScript/UrlHandler.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Value.cs, src/OpenSage.Game/Gui/Apt/AptCallbacksAttribute.cs, src/OpenSage.Game/Gui/Apt/AptInputMessageHandler.cs, src/OpenSage.Game/Gui/Apt/AptMainMenuSource.cs, src/OpenSage.Game/Gui/Apt/AptWindow.cs, src/OpenSage.Game/Gui/Apt/AptWindowManager.cs, src/OpenSage.Game/Gui/Apt/ButtonItem.cs, src/OpenSage.Game/Gui/Apt/DisplayList.cs, src/OpenSage.Game/Gui/Apt/SpriteItem.cs, src/OpenSage.Mods.Bfme2/Gui/AptMainMenu.cs, src/OpenSage.Mods.Bfme2/Gui/AptOptions.cs
- Implement more instructions
- Fix transitions
- Implement more callback functions
- Remove button debug overlay
=> Apt progress

src/OpenSage.Game/Terrain/Roads/RoadSegmentMesher.cs
Further improved road rendering in uneven terrain:
previous version had problems with bumps between the middle and the border of the road
old:
new:
=> uneven roads

src/OpenSage.Core/StringConverter.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/Logic/Object/Colliders.cs, src/OpenSage.Game/Logic/Object/Draw/W3dModelDraw.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/OrderGeneratorSystem.cs, src/OpenSage.Game/Logic/OrderGenerators/ConstructBuildingOrderGenerator.cs, src/OpenSage.Game/Logic/Orders/OrderProcessor.cs, src/OpenSage.Game/Logic/Player.cs, src/OpenSage.Game/Scene3D.cs, src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
* Adds the changing height to the build animation
* Adds the generals underconstruction state for the control bar
* Adds money to the game
* Moves builders to the construction place
=> Work on construction

src/OpenSage.Game.Tests/Mathematics/AngleTests.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Locomotor.cs, src/OpenSage.Game/Logic/Object/LocomotorTemplate.cs, src/OpenSage.Mathematics/MathUtility.cs
Allows gameobjects to not stick on the ground
=> Work on aircraft locomotors

src/OpenSage.Game/Content/ContentManager.cs, src/OpenSage.Game/Content/SubsystemLoader.cs, src/OpenSage.Game/Logic/Object/Locomotor.cs, src/OpenSage.Game/Logic/Object/LocomotorTemplate.cs, src/OpenSage.Game/Subsystem.cs
* Make sure locomotor.ini is loaded for BFME
* Use the speed specified inside the LocomotorSet
* Convert *TurnTime* into a *TurnRate* (TurnTime is used in BFME upwards)
=> Fix BFME locomotors crash

src/OpenSage.Game/Logic/OrderGenerators/ConstructBuildingOrderGenerator.cs, src/OpenSage.Game/Logic/OrderGenerators/TrainUnitOrderGenerator.cs, src/OpenSage.Game/Logic/Orders/OrderProcessor.cs
* Adds cashback when selling a unit
* Units do cost money
=> Add selling and unit cost

src/OpenSage.Game/Audio/AudioSystem.cs, src/OpenSage.Game/Logic/Object/ClientBehavior/ModelConditionSoundSelectorClientBehavior.cs, src/OpenSage.Game/Logic/Object/ObjectDefinition.cs, src/OpenSage.Game/Logic/Object/UnitSpecificSounds.cs, src/OpenSage.Game/Logic/OrderGeneratorInputHandler.cs, src/OpenSage.Game/Logic/OrderGeneratorSystem.cs, src/OpenSage.Game/Logic/OrderGenerators/ConstructBuildingOrderGenerator.cs, src/OpenSage.Game/Logic/OrderGenerators/IOrderGenerator.cs, src/OpenSage.Game/Logic/OrderGenerators/RallyPointOrderGenerator.cs, src/OpenSage.Game/Logic/OrderGenerators/TrainUnitOrderGenerator.cs, src/OpenSage.Game/Logic/Orders/OrderProcessor.cs, src/OpenSage.Game/Logic/Player.cs, src/OpenSage.Game/Scene3D.cs
Now the correct audio events are played when a building can / cannot be placed. And mouse-drag results in the correct rotation.
[![](http://img.youtube.com/vi/h0BrXLbQRiU/0.jpg)](http://www.youtube.com/watch?v=h0BrXLbQRiU "OpenSAGE - Placing buildings")
=> Improvements for placing buildings

src/OpenSage.Game/Terrain/Roads/CurvedRoadSegment.cs, src/OpenSage.Game/Terrain/Roads/RoadNetwork.cs, src/OpenSage.Game/Terrain/Roads/RoadTopology.cs
Connected road segments are now aligned (see https://github.com/OpenSAGE/OpenSAGE/issues/341#issuecomment-571703187 for details) so that their textures have the same orientation.
=> Road alignment

src/OpenSage.Game/Assets/Shaders/Sprite.frag, src/OpenSage.Game/Game.cs, src/OpenSage.Game/Graphics/Animation/AnimationInstance.cs, src/OpenSage.Game/Graphics/Shaders/SpriteShaderResources.cs, src/OpenSage.Game/Graphics/SpriteBatch.cs, src/OpenSage.Game/Gui/DrawingContext2D.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Update/ProductionUpdate.cs, src/OpenSage.Game/Logic/OrderGenerators/ConstructBuildingOrderGenerator.cs, src/OpenSage.Game/Scene3D.cs, src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
* Add radial progress indicator for production queue items
* Fix glitch in door opening / closing animations
* Fix animation mode bug
Now it looks like this: https://youtu.be/npAmf5YsLm8
=> Production improvements

src/OpenSage.Game/Graphics/Cameras/Camera.cs, src/OpenSage.Game/Gui/DrawingContext2D.cs, src/OpenSage.Game/Gui/SelectionGui.cs, src/OpenSage.Game/Logic/Object/Body/ActiveBody.cs, src/OpenSage.Game/Logic/Object/Body/BodyModule.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Player.cs, src/OpenSage.Game/Logic/SelectionMessageHandler.cs, src/OpenSage.Game/Logic/SelectionSystem.cs, src/OpenSage.Game/Scene3D.cs, src/OpenSage.Game/Scripting/LuaScriptEngine.cs, src/OpenSage.Mathematics/RectangleF.cs
Replaces the placeholder red boxes with somewhat-correct health bars: https://youtu.be/bVClsn7c-ls
I've also added a blue production queue bar under the health bar, which is a C&C3 feature that I really like: https://youtu.be/5pLeNDYDEr8
=> Health bars

src/OpenSage.Game/Assets/Shaders/Sprite.frag, src/OpenSage.Game/Data/Ini/IniParser.cs, src/OpenSage.Game/Graphics/Shaders/SpriteShaderResources.cs, src/OpenSage.Game/Graphics/SpriteBatch.cs, src/OpenSage.Game/Gui/DrawingContext2D.cs, src/OpenSage.Game/Gui/Wnd/Images/Image.cs, src/OpenSage.Game/Logic/Object/ObjectPrerequisites.cs, src/OpenSage.Game/Logic/Player.cs, src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
Implements object prerequisites, so we can gray out - and disable - buttons for stuff that can't be built.
=> Object prerequisites

src/OpenSage.Game/Game.cs, src/OpenSage.Launcher/Program.cs
Allow loading of replays captured on user maps.
=> User map replays

src/OpenSage.Game/Data/Ini/IniParser.cs, src/OpenSage.Game/Data/Rep/ReplayChunkHeader.cs, src/OpenSage.Game/FX/FXNuggets/SoundFXNugget.cs, src/OpenSage.Game/Logic/Object/BehaviorModule.cs, src/OpenSage.Game/Logic/Object/Behaviors/BezierProjectileBehavior.cs, src/OpenSage.Game/Logic/Object/Behaviors/InstantDeathBehavior.cs, src/OpenSage.Game/Logic/Object/Body/ActiveBody.cs, src/OpenSage.Game/Logic/Object/Body/BodyModule.cs, src/OpenSage.Game/Logic/Object/Die/DestroyDie.cs, src/OpenSage.Game/Logic/Object/Die/DieModule.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Locomotor.cs, src/OpenSage.Game/Logic/Object/ObjectDefinition.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/AIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/DozerAIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/MissileAIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/TransportAIUpdate.cs, src/OpenSage.Game/Logic/Object/Weapon/Weapon.cs, src/OpenSage.Game/Logic/Object/Weapon/WeaponEffects/DamageNugget.cs, src/OpenSage.Game/Logic/Object/Weapon/WeaponEffects/ProjectileNugget.cs, src/OpenSage.Game/Logic/Object/Weapon/WeaponStates/FiringWeaponState.cs, src/OpenSage.Game/Logic/Object/Weapon/WeaponStates/WeaponStateMachine.cs, src/OpenSage.Game/Logic/Object/Weapon/WeaponTarget.cs, src/OpenSage.Game/Logic/Object/Weapon/WeaponTemplate.cs
With these changes, Patriot missiles "sort of" work, with a very strong emphasis on "sort of" 😄
=> Weapons Part 5

src/OpenSage.Game/Graphics/ParticleSystems/ParticleSystem.cs, src/OpenSage.Game/Logic/Object/Behaviors/BezierProjectileBehavior.cs, src/OpenSage.Game/Logic/Object/Body/ActiveBody.cs, src/OpenSage.Game/Logic/Object/Body/HighlanderBody.cs, src/OpenSage.Game/Logic/Object/Body/InactiveBody.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Scene3D.cs
=> Fix some BFME II crashes

src/OpenSage.Game/Configuration.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/Gui/Wnd/Controls/Control.cs, src/OpenSage.Game/Gui/Wnd/Controls/ListBox.cs, src/OpenSage.Game/Network/LobbyBroadcastSession.cs, src/OpenSage.Game/Network/LobbyManager.cs, src/OpenSage.Game/Network/LobbyProtocol.cs, src/OpenSage.Game/Network/LobbyScanSession.cs, src/OpenSage.Launcher/Program.cs, src/OpenSage.Mods.Generals/Gui/LanGameOptionsMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/LanLobbyMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/NetworkDirectConnectCallbacks.cs, src/OpenSage.Mods.Generals/Gui/OptionsMenuCallbacks.cs
Overhaul of the previous implementation, seems to work in principle.
=> Network prototype

src/OpenSage.Game/Diagnostics/AssetViews/SoundView.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Library/Builtin.cs, src/OpenSage.Game/Gui/Apt/ActionScript/ObjectContext.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Opcodes/Arithmetic.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Opcodes/Basic.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Opcodes/Function.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Opcodes/Logic.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Opcodes/Object.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Opcodes/Stack.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Opcodes/String.cs, src/OpenSage.Game/Gui/Apt/ActionScript/VM.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Value.cs, src/OpenSage.Game/Gui/Apt/AptWindow.cs, src/OpenSage.Game/Gui/Apt/AptWindowManager.cs, src/OpenSage.Game/Logic/Object/Weapon/WeaponEffects/DamageNugget.cs, src/OpenSage.Mods.Bfme/Gui/AptMainMenu.cs, src/OpenSage.Mods.Bfme2/Gui/AptMainMenu.cs, src/OpenSage.Mods.Bfme2/Gui/AptSkirmish.cs, src/OpenSage.Mods.Bfme2/Gui/MpGameSetup.cs
- add more instructions
- allow embedding apts into each other
- some fixes
=> Apt embedding

src/Directory.Build.props, src/OpenSage.Game/GameWindow.cs, src/OpenSage.Game/Gui/TextCache.cs, src/OpenSage.Game/OpenSage.Game.csproj, src/OpenSage.Game/Terrain/Terrain.cs, src/OpenSage.Game/Utilities/Extensions/ResourceFactoryExtensions.cs
=> Dep updates

src/OpenSage.Game/Data/Ini/IniParser.Enums.cs, src/OpenSage.Game/Diagnostics/InspectorView.cs, src/OpenSage.Game/Diagnostics/MainView.cs, src/OpenSage.Game/Diagnostics/Util/ImGuiUtility.cs, src/OpenSage.Game/Logic/Object/BehaviorModule.cs, src/OpenSage.Game/Logic/Object/Behaviors/BezierProjectileBehavior.cs, src/OpenSage.Game/Logic/Object/Behaviors/PhysicsBehavior.cs, src/OpenSage.Game/Logic/Object/Behaviors/SlowDeathBehavior.cs, src/OpenSage.Game/Logic/Object/Body/ActiveBody.cs, src/OpenSage.Game/Logic/Object/Body/BodyModule.cs, src/OpenSage.Game/Logic/Object/Body/HighlanderBody.cs, src/OpenSage.Game/Logic/Object/Body/InactiveBody.cs, src/OpenSage.Game/Logic/Object/Draw/DrawModule.cs, src/OpenSage.Game/Logic/Object/Draw/W3dDebrisDraw.cs, src/OpenSage.Game/Logic/Object/Draw/W3dModelDraw.cs, src/OpenSage.Game/Logic/Object/Draw/W3dTankDraw.cs, src/OpenSage.Game/Logic/Object/Draw/W3dTruckDraw.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/AIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/ProductionUpdate.cs, src/OpenSage.Game/Logic/Object/Weapon/Weapon.cs, src/OpenSage.Game/Logic/Object/Weapon/WeaponEffects/DamageNugget.cs, src/OpenSage.Game/Logic/Object/Weapon/WeaponEffects/WeaponEffectExecutionContext.cs, src/OpenSage.Game/Logic/Object/Weapon/WeaponStates/BaseWeaponState.cs, src/OpenSage.Game/Logic/Object/Weapon/WeaponStates/FiringWeaponState.cs, src/OpenSage.Game/Logic/Object/Weapon/WeaponStates/FixedDurationWeaponState.cs, src/OpenSage.Game/Logic/Object/Weapon/WeaponStates/WeaponStateMachine.cs, src/OpenSage.Game/Logic/Object/Weapon/WeaponTarget.cs, src/OpenSage.Game/Scene3D.cs
* Inspector diagnostic view
* `SlowDeathBehavior`
* Started to do a little on `W3DTankDraw`
=> Inspector diagnostic view and SlowDeathBehavior

src/OpenSage.Game/Terrain/Roads/CurvedRoadSegment.cs, src/OpenSage.Game/Terrain/Roads/RoadSegmentMesher.cs, src/OpenSage.Game/Terrain/Roads/RoadTopology.cs, src/OpenSage.Game/Terrain/Roads/TextureAtlas.cs
* Ignore duplicate road segments
* Texture coordinate fixes
* Use same triangle indices as original SAGE
=> Road bugfixes

src/OpenSage.Game/Game.cs, src/OpenSage.Game/Graphics/ParticleSystems/ParticleSystem.cs, src/OpenSage.Game/Logic/Object/BehaviorModule.cs, src/OpenSage.Game/Logic/Object/Behaviors/BezierProjectileBehavior.cs, src/OpenSage.Game/Logic/Object/Behaviors/InstantDeathBehavior.cs, src/OpenSage.Game/Logic/Object/Behaviors/PhysicsBehavior.cs, src/OpenSage.Game/Logic/Object/Behaviors/SlowDeathBehavior.cs, src/OpenSage.Game/Logic/Object/Body/BodyModule.cs, src/OpenSage.Game/Logic/Object/Damage/TransitionDamageFX.cs, src/OpenSage.Game/Logic/Object/Die/CreateObjectDie.cs, src/OpenSage.Game/Logic/Object/Die/DestroyDie.cs, src/OpenSage.Game/Logic/Object/Die/FXListDie.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/AIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/ProductionExit/DefaultProductionExitUpdate.cs, src/OpenSage.Game/Logic/Object/Update/ProductionExit/QueueProductionExitUpdate.cs, src/OpenSage.Game/Logic/Object/Update/ProductionExit/SpawnPointProductionExitUpdate.cs, src/OpenSage.Game/Logic/Object/Update/ProductionExit/SupplyCenterProductionExitUpdate.cs, src/OpenSage.Game/Logic/Object/Update/ProductionUpdate.cs, src/OpenSage.Game/Logic/Object/Update/WeaponSetUpdate.cs, src/OpenSage.Game/Logic/Object/Upgrade/ExperienceScalarUpgrade.cs, src/OpenSage.Game/Logic/Object/Upgrade/MaxHealthUpgrade.cs, src/OpenSage.Game/Logic/Object/Upgrade/PowerPlantUpgrade.cs, src/OpenSage.Game/Logic/Object/Upgrade/WeaponBonusUpgrade.cs, src/OpenSage.Game/Logic/Object/Upgrade/WeaponSetUpgrade.cs
* Fix crash on launch for en-US
* Use `GravityMult` and add defaults for both `GravityMult` and `Mass`
* Fix `maxParticles` calculation
=> Fixes for BFME II

src/OpenSage.Game/Content/ContentManager.cs, src/OpenSage.Game/Content/SubsystemLoader.cs, src/OpenSage.Game/Logic/OrderGeneratorSystem.cs, src/OpenSage.Game/Logic/OrderGenerators/SpecialPowerOrderGenerator.cs, src/OpenSage.Game/Logic/Orders/Order.cs, src/OpenSage.Game/Logic/Orders/OrderProcessor.cs, src/OpenSage.Game/Logic/Orders/OrderType.cs, src/OpenSage.Game/Subsystem.cs, src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
- Implement the ordertypes
- Handle CommandButton Commands
- Add an SpecialPowerOrderGenerator
- Throw an exception on the orders for now
=> Start work on specialpowers

src/OpenSage.Game/Data/Map/NamedCamera.cs, src/OpenSage.Game/Logic/Object/Behaviors/BezierProjectileBehavior.cs, src/OpenSage.Game/Logic/Object/Body/ActiveBody.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Scripting/Actions/CameraActions.cs
- Set initial health correctly for BFME gameobjects
- Prevent projectilebehavior for non-projectiles
- Read more fields of the NamedCamera
=> Bfme fixes

src/OpenSage.Game/Data/Ini/IniParser.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/Gui/DebugUI/DebugMessageHandler.cs, src/OpenSage.Game/Gui/DebugUI/DebugOverlay.cs, src/OpenSage.Game/Input/HandlingPriority.cs, src/OpenSage.Game/Logic/Object/AnimationState.cs, src/OpenSage.Game/Logic/Object/Behaviors/ParkingPlaceBehavior.cs, src/OpenSage.Game/Logic/Object/Behaviors/PhysicsBehavior.cs, src/OpenSage.Game/Logic/Object/Colliders.cs, src/OpenSage.Game/Logic/Object/Draw/W3dTruckDraw.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Locomotor.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/AIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/ProductionUpdate.cs, src/OpenSage.Game/Logic/Object/Weapon/WeaponEffects/DamageNugget.cs, src/OpenSage.Game/Logic/OrderGenerators/ConstructBuildingOrderGenerator.cs, src/OpenSage.Game/Logic/Orders/OrderProcessor.cs, src/OpenSage.Game/Logic/Orders/OrderType.cs, src/OpenSage.Game/Navigation/Graph.cs, src/OpenSage.Game/Navigation/Navigation.cs, src/OpenSage.Game/Navigation/PathOptimizer.cs, src/OpenSage.Game/Terrain/HeightMap.cs, src/OpenSage.Game/Transform.cs, src/OpenSage.Mathematics/ColorRgbaF.cs, src/OpenSage.Mathematics/TransformedRectangle.cs, src/OpenSage.Mathematics/TriangleUtility.cs, src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
- front tire rotation
- turn radius
- terrain alignment
- bounce dampening
- different turns for Tread & FourWheel handling
- cancel unit order
- cancel construction order
- basic/dummy parking place behavior (for airfields)
- navigation takes care of obstacles 
- fixed animation loading for various bfme2 models
=> Various improvements

src/OpenSage.Game/Data/Ini/IniParser.cs, src/OpenSage.Game/Logic/Object/Draw/W3dTreeDraw.cs
=> Implement simple tree draw module

src/OpenSage.Game/Data/Ini/IniParser.BlockParsers.cs, src/OpenSage.Game/Logic/Object/Behaviors/CastleBehavior.cs, src/OpenSage.Game/Logic/Object/Draw/W3dFloorDraw.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/ObjectDefinition.cs, src/OpenSage.Game/Network/SkirmishManager.cs, src/OpenSage.Game/Scene3D.cs
I still need to figure out the correct transformation, that why i open this as a draft for now
=> Improve castle appearance

src/OpenSage.FileFormats/BinaryReaderExtensions.cs, src/OpenSage.Game/Assets/Shaders/Cloud.h, src/OpenSage.Game/Content/Loaders/OnDemandAnimationLoader.cs, src/OpenSage.Game/Content/Translation/TranslationManager.cs, src/OpenSage.Game/Data/Ini/IniParser.cs, src/OpenSage.Game/Data/Map/EnvironmentData.cs, src/OpenSage.Game/Graphics/Animation/W3DAnimation.cs, src/OpenSage.Game/Graphics/ModelMesh.W3d.cs, src/OpenSage.Game/Graphics/TextureAsset.cs, src/OpenSage.Game/Logic/Object/Draw/W3dFloorDraw.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Navigation/Navigation.cs, src/OpenSage.Game/Terrain/Roads/RoadSegmentMesher.cs, src/OpenSage.Game/Terrain/Terrain.cs, src/OpenSage.Game/Utilities/LanguageUtility.cs
A lot of bfme, bfme2 and rotwk maps crash when we attempt to load them. 
These small fixes allow us to load most of them.
=> Bfme2 map improvements

src/OpenSage.Game/Assets/Shaders/RadiusCursorDecals.h, src/OpenSage.Game/Assets/Shaders/RadiusCursorDecalsFunctions.h, src/OpenSage.Game/Assets/Shaders/Road.frag, src/OpenSage.Game/Assets/Shaders/Terrain.frag, src/OpenSage.Game/Content/ContentManager.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/Graphics/Shaders/RadiusCursorDecalShaderResources.cs, src/OpenSage.Game/Graphics/Shaders/RoadShaderResources.cs, src/OpenSage.Game/Graphics/Shaders/ShaderResourceManager.cs, src/OpenSage.Game/Graphics/Shaders/TerrainShaderResources.cs, src/OpenSage.Game/Graphics/StandardGraphicsResources.cs, src/OpenSage.Game/Gui/InGame/InGameUI.cs, src/OpenSage.Game/Logic/OrderGeneratorSystem.cs, src/OpenSage.Game/Logic/OrderGenerators/SpecialPowerOrderGenerator.cs, src/OpenSage.Game/Scene3D.cs, src/OpenSage.Game/Terrain/RadiusCursorDecal.cs, src/OpenSage.Game/Terrain/RadiusCursorDecals.cs, src/OpenSage.Game/Terrain/Roads/Road.cs, src/OpenSage.Game/Terrain/Roads/RoadCollection.cs, src/OpenSage.Game/Terrain/Terrain.cs, src/OpenSage.Game/Terrain/TerrainPatch.cs
=> Radius cursors

src/OpenSage.Game/Assets/Shaders/Terrain.frag, src/OpenSage.Game/Content/IPathResolver.cs, src/OpenSage.Game/Graphics/Shaders/TerrainShaderResources.cs, src/OpenSage.Game/Scene3D.cs, src/OpenSage.Game/Terrain/Terrain.cs, src/OpenSage.Game/Terrain/TerrainPatch.cs
I can't detect any visual difference between caustics on / off, but at least they don't cause a ~megabytes per second memory leak now.
=> Fix memory leak

src/OpenSage.Game/Data/Ini/TokenReader.cs, src/OpenSage.Mathematics/BitArray`1.cs
On my computer, these changes reduce startup time by 5% or so.
=> Some perf tweaks

src/OpenSage.Game/Game.cs, src/OpenSage.Game/Network/LobbyManager.cs, src/OpenSage.Game/Network/NetworkConnection.cs, src/OpenSage.Game/Network/SkirmishGame.cs, src/OpenSage.Game/Network/SkirmishManager.cs, src/OpenSage.Game/Network/SkirmishSlot.cs, src/OpenSage.Mods.Generals/Gui/GameOptionsUtil.cs, src/OpenSage.Mods.Generals/Gui/LanGameOptionsMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/LanLobbyMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/NetworkDirectConnectCallbacks.cs
I've rewritten the lobby communication to make a bit more sense (most notably I've split the Host/Client part). Current state is that color, faction and team syncs.
=> Networking lobby

src/OpenSage.FileFormats.Big/BigArchive.cs, src/OpenSage.Game/Data/Ini/IniParser.cs, src/OpenSage.Game/Graphics/ModelInstance.cs, src/OpenSage.Game/Graphics/ModelMesh.cs, src/OpenSage.Game/Logic/Object/Behaviors/ParkingPlaceBehavior.cs, src/OpenSage.Game/Logic/Object/Behaviors/PhysicsBehavior.cs, src/OpenSage.Game/Logic/Object/Body/ActiveBody.cs, src/OpenSage.Game/Logic/Object/Draw/W3dModelDraw.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Locomotor.cs, src/OpenSage.Game/Logic/Object/LocomotorTemplate.cs, src/OpenSage.Game/Logic/Object/ModelConditionState.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/AIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/JetAIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/ProductionUpdate.cs, src/OpenSage.Game/Logic/Object/Weapon/WeaponEffects/DamageNugget.cs, src/OpenSage.Game/Navigation/Graph.cs, src/OpenSage.Game/Navigation/PathOptimizer.cs, src/OpenSage.Game/Transform.cs, src/OpenSage.Mathematics/MathUtility.cs, src/OpenSage.Mathematics/Percentage.cs, src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
The ParkingPlaceBehavior is not finished by any means, but this is a good basis we can improve upon.
E.g. landing of jets/aircrafts is not yet dealt with etc.
- some improvements and cleanup in the Locomotor class
- implement initial aircraft taxiing, starting and very basic landing on both airfields (us and china)
- added a method to check if a object can produce the requested object/upgrade
- jets maintain position by circling around at the target point (idle time) and return to base after that
- close the airfield hangar door only when the corresponding jet dies
=> ParkingPlaceBehaviour

src/OpenSage.Game/Logic/Object/Update/AIUpdate/AIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/JetAIUpdate.cs
- fix crashes of ZH shellmap (locomotorSet  is null / JetAIUpdate.Base is null)
=> Shellmap fixes

src/OpenSage.Game/Input/Cursors/Cursor.cs
This should remove a lot of CPU-load from the cursor update
=> Prevent super-fast-cursor

src/OpenSage.FileFormats.Big/BigArchive.cs, src/OpenSage.Launcher/OpenSage.Launcher.csproj, src/OpenSage.Tools.BigTool/OpenSage.Tools.BigTool.csproj, src/OpenSage.Tools.BigTool/Program.cs, src/OpenSage.sln
Adds a CLI tool to pack & unpack big archives. Similar to the linux **zip** command
=> Big pack CLI tool

NuGet.config, src/Directory.Build.props, src/OpenSage.Game/Audio/AudioSystem.cs, src/OpenSage.Game/Diagnostics/AssetViews/SoundView.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/OrderGenerators/ConstructBuildingOrderGenerator.cs, src/OpenSage.Game/OpenSage.Game.csproj
=> Implement Submixing & 3D Audio

src/OpenSage.Game/Content/SubsystemLoader.cs, src/OpenSage.Game/Diagnostics/MainView.cs, src/OpenSage.Game/Gui/CommandButtonCallback.cs, src/OpenSage.Game/Logic/ExperienceLevel.cs, src/OpenSage.Game/Logic/Object/Behaviors/SpawnBehavior.cs, src/OpenSage.Game/Logic/Object/Behaviors/SpawnUnitBehavior.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Locomotor.cs, src/OpenSage.Game/Logic/Object/ObjectDefinition.cs, src/OpenSage.Game/Logic/Object/StanceTemplate.cs, src/OpenSage.Game/Logic/Object/Update/AutoDepositUpdate.cs, src/OpenSage.Game/Logic/Object/Update/BannerCarrierUpdate.cs, src/OpenSage.Game/Logic/Object/Update/ExperienceUpdate.cs, src/OpenSage.Game/Logic/Object/Update/ProductionUpdate.cs, src/OpenSage.Game/Logic/Object/Upgrade/SubObjectsUpgrade.cs, src/OpenSage.Game/Scene3D.cs, src/OpenSage.Game/Scripting/ScriptingSystem.cs
Structures gain now experience when they generate ressources or produce units.
Structures and units level up accordingly to the gained experience.
=> Experience

src/OpenSage.Game/Diagnostics/AssetViews/GameObjectView.cs, src/OpenSage.Game/Logic/Object/GameObjectCollection.cs
- since the objects where only added to the 'createList' but never actually added to the ObjectCollection the preview was always empty.
=> fixed objects not shown in preview

src/OpenSage.Core/DisposableBase.cs, src/OpenSage.Game/Data/Ini/IniParser.cs, src/OpenSage.Game/Graphics/ModelInstance.cs, src/OpenSage.Game/Logic/Object/AnimationState.cs, src/OpenSage.Game/Logic/Object/Draw/DrawModule.cs, src/OpenSage.Game/Logic/Object/Draw/W3DSailModelDraw.cs, src/OpenSage.Game/Logic/Object/Draw/W3dDebrisDraw.cs, src/OpenSage.Game/Logic/Object/Draw/W3dFloorDraw.cs, src/OpenSage.Game/Logic/Object/Draw/W3dHordeModelDraw.cs, src/OpenSage.Game/Logic/Object/Draw/W3dModelDraw.cs, src/OpenSage.Game/Logic/Object/Draw/W3dScriptedModelDraw.cs, src/OpenSage.Game/Logic/Object/Draw/W3dTreeDraw.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/IniScript.cs, src/OpenSage.Game/Logic/Object/TransitionState.cs, src/OpenSage.Game/Logic/Object/Upgrade/SubObjectsUpgrade.cs, src/OpenSage.Game/Scripting/LuaScriptEngine.cs
- parse lua code in AnimationStates
- hide drawModules accordingly
=> Process lua code in AnimationStates

src/OpenSage.Game/Graphics/Shaders/GlobalShaderResources.cs, src/OpenSage.Game/Graphics/StandardGraphicsResources.cs
Add name for the sampler objects to make it easier to debug in OpenGL at least.
=> Add Name for Sampler Objects

src/OpenSage.Game/Content/Translation/LocalizedString.cs, src/OpenSage.Game/Gui/Apt/RenderItem.cs
Fixes apt text in a less clunky way
=> less clunky apt text fix

src/OpenSage.Game/Content/ContentManager.cs, src/OpenSage.Game/Data/FileSystem.cs, src/OpenSage.Game/Data/Map/UserMapCache.cs, src/OpenSage.Game/Diagnostics/Util/DistinctLogger.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/Scene3D.cs
Let OpenSage search for maps in `%appdata%\{UserDataLeafName}\Maps` for games from CNC3 onward.
=> Trying to handle loading of custom maps

docs/map-position-selection.md, src/OpenSage.Game/Game.cs, src/OpenSage.Game/Logic/PlayerSettings.cs, src/OpenSage.Game/Network/SkirmishSlot.cs, src/OpenSage.Mods.Generals/Gui/GameOptionsUtil.cs, src/OpenSage.Mods.Generals/Gui/LanGameOptionsMenuCallbacks.cs
Highly uncertain about the LAN side of this, but tested a solo skirmish lobby and as far as I can tell it works as expected.
=> Fix #321 add map position selection

NuGet.config
- Fix build by removing non-existant package sources
=> Remove unused NuGet package sources

src/OpenSage.Game/Graphics/Cameras/CameraInputMessageHandler.cs, src/OpenSage.Game/Graphics/Cameras/RtsCameraController.cs, src/OpenSage.Game/Logic/OrderGeneratorInputHandler.cs, src/OpenSage.Game/Logic/SelectionMessageHandler.cs, src/OpenSage.Game/Logic/SelectionSystem.cs, src/OpenSage.Game/Terrain/HeightMap.cs
This should bring the right-click camera pan system more closely in line with Generals/ZH.
=> Fix right click camera pan behavior

src/OpenSage.Game/Game.cs, src/OpenSage.Game/Gui/Wnd/WndWindowManager.cs, src/OpenSage.Game/Network/LobbyManager.cs, src/OpenSage.Game/Network/Packets/PacketType.cs, src/OpenSage.Game/Network/Packets/SkirmishClientConnectPacket.cs, src/OpenSage.Game/Network/Packets/SkirmishClientReadyPacket.cs, src/OpenSage.Game/Network/Packets/SkirmishClientUpdatePacket.cs, src/OpenSage.Game/Network/SkirmishManager.cs, src/OpenSage.Game/Network/SkirmishSlot.cs, src/OpenSage.Mods.Generals/Gui/GameOptionsUtil.cs, src/OpenSage.Mods.Generals/Gui/LanGameOptionsMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/LanLobbyMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/LanMapSelectMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/SkirmishMapSelectMenuCallbacks.cs
* Ready status for clients (disables UI, resets when anything changes)
* Switch to new map only when OK is clicked
* Handle disconnects (in menu, not in game)
* `Update` method in `SkirmishManager` for handling stuff on the main thread
* Show message when trying to connect to a game that is already full
=> Skirmish improvements

.github/workflows/ci.yml, NuGet.config, src/OpenSage.Game.CodeGen/OpenSage.Game.CodeGen.csproj, src/OpenSage.Game.CodeGen/ScriptActionsGenerator.cs, src/OpenSage.Game.CodeGen/ScriptConditionsGenerator.cs, src/OpenSage.Game.CodeGen/ScriptContentGeneratorBase.cs, src/OpenSage.Game/Graphics/Cameras/ArcballCameraController.cs, src/OpenSage.Game/Graphics/Cameras/CameraAnimation.cs, src/OpenSage.Game/Graphics/Cameras/ICameraController.cs, src/OpenSage.Game/Graphics/Cameras/RtsCameraController.cs, src/OpenSage.Game/OpenSage.Game.csproj, src/OpenSage.Game/Scripting/Actions/ScriptActions.Camera.cs, src/OpenSage.Game/Scripting/Actions/ScriptActions.cs, src/OpenSage.Game/Scripting/Conditions/ScriptConditionAttribute.cs, src/OpenSage.Game/Scripting/Conditions/ScriptConditions.cs, src/OpenSage.sln
Now we generate binding code that looks like this:
based on attributed script conditions and actions that look like this:
=> Use source generators to create binding code for script actions and conditions

.github/dependabot.yml, src/OpenSage.Core/OpenSage.Core.csproj, src/OpenSage.Game.Tests/OpenSage.Game.Tests.csproj, src/OpenSage.Game/OpenSage.Game.csproj, src/OpenSage.Tools.BigTool/OpenSage.Tools.BigTool.csproj
Will make it a bit simpler to keep up with any dependency upgrades. We can probably squash this once initially
=> Upgrade all dependencies and add dependabot

src/OpenSage.Game/Content/ContentManager.cs, src/OpenSage.Game/Logic/Object/UpgradeTemplate.cs
Another thing discovered while parsing .sav files - the engine creates default upgrades for veterancy levels.
=> Create default upgrades

src/OpenSage.Game/Graphics/Shaders/ShaderSet.cs
Reduces shader initialisation at startup, on my computer, from 1.3s to 50ms.
=> Cache cross-compiled shaders for target platform

.github/workflows/ci.yml, src/OpenSage.Game.CodeGen/ScriptActionsGenerator.cs, src/OpenSage.Game.CodeGen/ScriptConditionsGenerator.cs, src/OpenSage.Game.Tests/OpenSage.Game.Tests.csproj
Eventhough our testing isn't fully functional yet in CI (only a small amount of tests executed), it has become super easy with .NET 5 to calculate coverage statistics.
=> Readd coverage calculation

src/OpenSage.Game/Graphics/Rendering/Shadows/ShadowMapRenderer.cs, src/OpenSage.Game/SageGame.cs, src/OpenSage.Tools.AptEditor/AptEditorDefinition.cs, src/OpenSage.Tools.AptEditor/Program.cs, src/OpenSage.Tools.AptEditor/UI/AptFileSelector.cs
Added a new `SageGame` type for AptEditor since it's not an actual game.
But yes, we should decouple it from the game in the long term...
=> Make AptEditor Go Again

src/OpenSage.Game/Data/Map/SidesListUtility.cs, src/OpenSage.Game/Data/Scb/ScbFile.cs, src/OpenSage.Game/Data/Scb/ScriptPlayer.cs, src/OpenSage.Game/Data/Scb/ScriptsPlayer.cs, src/OpenSage.Game/Data/Scb/ScriptsPlayers.cs
Adds conditional parsing of player properties for ScriptsPlayers.
=> Parse ScriptsPlayers properties

src/OpenSage.Game/Logic/Object/ObjectDefinition.cs, src/OpenSage.Game/Logic/OrderGenerators/UnitOrderGenerator.cs, src/OpenSage.Game/Logic/SelectionSystem.cs
We had multiple bugs introduced in BFME: 
- The game did not work when there was no LocalPlayer. However the BFME Shellmap only has a CivilianPlayer / non human players
- Locomotors can be overwritten
=> Fix game not working without local player

src/OpenSage.Launcher/Program.cs
Added the name for each possible graphic backend, perhaps making it a bit easier for the user to know what argument it can handle.
=> Added name for each graphic backend

src/OpenSage.Game/GameData.cs
I hope, i did these properties in the correct file. ^^
=> Added some map-properties for Bfme 1

docs/developer-guide.md, src/OpenSage.Game/IO/BigFileSystem.cs, src/OpenSage.Game/IO/DiskFileSystem.cs, src/OpenSage.Game/Input/Cursors/CursorManager.cs
This gets Generals running on ubuntu. The cursors bit was a bit puzzling. There might be a cleaner way to do that, I'm not sure.
Of note, the audio can be choppy at times on my machine and the unit select voice lines are very choppy. Otherwise, everything else seems to work exactly as it does on Windows!
=> Enable development on ubuntu

src/OpenSage.Game/Gui/ControlBar/CommandSet.cs, src/OpenSage.Game/Logic/Object/Draw/W3dModelDraw.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
Just a couple of NPEs prevented zero hour from running. I figured there's no harm in putting some checks around them and getting it running, even if the controlbar is a mess.
=> Get zero hour running

.gitignore, .vscode/launch.json, src/OpenSage.Game/Gui/Wnd/WndWindowManager.cs, src/OpenSage.Game/Radar.cs, src/OpenSage.Launcher/Program.cs, src/OpenSage.Mods.Generals/Gui/ControlBarCallbacks.cs, src/OpenSage.Mods.Generals/Gui/SharedCallbacks.cs, src/OpenSage.Tools.BigEditor/UI/MainForm.cs
- Add ShaderCache and DeveloperMode.ini to gitignore
- Log a warning when startup map is missing from map cache
- Fix general upgrade menu being able to opened multiple times
- Add option to BigEditor to open an archive in read-only mode
- Add VS Code launch config to start Generals in Alpine Assault
=> A pile of various small fixes

src/OpenSage.Game/Logic/Object/ObjectCreationList.cs
Relates to #730 as this now factors in the `Count` parameter
=> Create proper count of objects in ObjectCreationList

src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
=> Fix control bar empty

src/OpenSage.Game/Logic/Object/Create/VeterancyGainCreate.cs
Sometimes VeterancyGainCreate does not require any science
=> Fix unable to build demo truck

src/OpenSage.Game/Logic/AI/StateMachineBase.cs, src/OpenSage.Game/Logic/Object/Locomotor.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/AIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/WorkerAIUpdate.cs
Came across these when I was trying to figure out some of the container behavior.
[workeraistatemachine.zip](https://github.com/OpenSAGE/OpenSAGE/files/13999506/workeraistatemachine.zip)
sav 14 has state machine 2, and 15 has state machine 3.
=> Add new WorkerAIUpdate state machines

src/OpenSage.Game/Scene3D.cs, src/OpenSage.Mathematics/RectangleF.cs
=> Show unit veterancy in world

src/OpenSage.Game/Logic/Object/GameObject.cs
I noticed in a different feature I was working on that as I was calling `FindBehavior` quite often it was allocating lots of memory. Figured I'd go ahead and implement some sort of caching to hopefully reduce that.
=> Cache GameObject.BehaviorModules by type for fast access

src/OpenSage.Game/Logic/Object/SpecialPower/CleanupAreaPower.cs, src/OpenSage.Game/Logic/Object/Update/CleanupHazardUpdate.cs
Was testing some other behavior (`AutoHealBehavior`) and came across a couple of modules which weren't defined yet. No idea what the contents of them are, but figured at least I'd get them in.
=> Scaffold core behaviors for CleanupAreaPower and CleanupHazardUpdate

src/OpenSage.Tools.BigEditor/OpenSage.Tools.BigEditor.csproj, src/OpenSage.Tools.BigEditor/UI/MainForm.cs
Looks like this isn't included in the CI checks - do we want to add one?
=> Fix BigEditor not compiling

src/OpenSage.Game/Logic/Object/GameObject.cs
No idea what this byte is for, but maybe the extra comments will help somebody figure it out someday lol
=> Persist unknown byte in PolygonTriggerState

src/OpenSage.Game/Logic/AI/AIPlayer.cs, src/OpenSage.Game/Logic/Object/Behaviors/PhysicsBehavior.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/JetAIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/StickyBombUpdate.cs
A few more different field values I found while parsing saves looking for other things
=> Persist more alternate field values

src/OpenSage.Game/Logic/Object/Body/ActiveBody.cs, src/OpenSage.Game/Logic/Object/Body/BodyModule.cs, src/OpenSage.Game/Logic/Object/Body/InactiveBody.cs, src/OpenSage.Game/Logic/Object/Update/UpdateModule.cs
Just a couple of items I found missing from the inspector view that help with debugging
=> Inspector updates

src/OpenSage.Game/Logic/Object/GameObject.cs
Are these upgrade names consistent across games? I don't see them defined anywhere as constants in Generals...
=> Apply veterancy upgrade on rank change

src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
I'm really not sure what the best way to handle this one is. It was discussed on discord a little bit, and I just find it weird that this is what generals does in the first place.
=> Set default CommandSet for garrisonable civilian buildings

src/OpenSage.Game/Radar.cs
Not sure if this is a thing in bfme? But if not, it should just be a no-op.
=> Draw hero reticle on radar

src/OpenSage.Game/Logic/Object/Contain/TunnelContain.cs
The base method was updated in a separate pr from this override being added
=> Fix compile failure

src/OpenSage.Game/Logic/Object/Collide/ConvertToHijackedVehicleCrateCollide.cs, src/OpenSage.Game/Logic/Object/Collide/CrateCollideModuleData.cs, src/OpenSage.Game/Logic/Object/Die/CreateCrateDie.cs, src/OpenSage.Game/Logic/Object/Die/CrushDie.cs, src/OpenSage.Game/Logic/Object/Die/KeepObjectDie.cs, src/OpenSage.Game/Logic/Object/Die/RebuildHoleExposeDie.cs, src/OpenSage.Game/Logic/Object/Update/DynamicShroudClearingRangeUpdate.cs, src/OpenSage.Game/Logic/Object/Update/HijackerUpdate.cs, src/OpenSage.Game/Logic/Object/Update/SlavedUpdate.cs
Adding a few missing overrides so sav file parsing doesn't crash.
=> Add missing die module constructors to allow sav parsing

src/OpenSage.Game/Logic/GameLogic.cs
Came across this while testing out some ObjectStatus stuff.
=> Parse objects being sold in sav file

src/OpenSage.Game/Logic/Object/Update/SlavedUpdate.cs, src/OpenSage.Mods.Bfme/Gui/AptControlBarSource.cs, src/OpenSage.Rendering/MaterialPass.cs, src/OpenSage.Rendering/RenderScene.cs
Combined with #842 this should get BFME2 running.
=> Fix various BFME2 NPEs

src/OpenSage.Game/Logic/PlayerManager.cs
=> Fix Neutral is everybody's ally and enemy

src/OpenSage.Game/Client/ColorFlashHelper.cs, src/OpenSage.Game/Client/Drawable.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Player.cs
The flash doesn't look _perfect_ (compared to vanilla generals), but it's a start.
=> Implement unit flash on selection

src/OpenSage.Game/Audio/AudioSystem.cs, src/OpenSage.Game/Gui/CommandButtonCallback.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/SpecialPower/CashHackSpecialPower.cs, src/OpenSage.Game/Logic/Object/SpecialPower/IUpgradableScienceModule.cs, src/OpenSage.Game/Logic/Object/SpecialPower/OCLSpecialPower.cs, src/OpenSage.Game/Logic/Object/SpecialPower/SpecialPower.cs, src/OpenSage.Game/Logic/Object/Update/BattlePlanUpdate.cs, src/OpenSage.Game/Logic/Object/Update/StealthDetectorUpdate.cs, src/OpenSage.Game/Logic/OrderGeneratorSystem.cs, src/OpenSage.Game/Logic/OrderGenerators/SpecialPowerOrderGenerator.cs, src/OpenSage.Game/Logic/Orders/Order.cs, src/OpenSage.Game/Logic/Orders/OrderProcessor.cs, src/OpenSage.Game/Logic/Orders/SpecialPower/SpecialPowerApplicator.cs, src/OpenSage.Game/Logic/Orders/SpecialPower/SpecialPowerAtLocationApplicator.cs, src/OpenSage.Game/Logic/Orders/SpecialPower/SpecialPowerAtObjectApplicator.cs, src/OpenSage.Game/Logic/Player.cs, src/OpenSage.Game/Radar.cs, src/OpenSage.Game/Terrain/HeightMap.cs
This sets up a framework for implementing special powers, and adds basic implementation for at least one of each type.
Changing the strategy center strategy actually works, which is pretty neat! I plan to tackle more special powers in time.
=> Begin special power implementation

src/OpenSage.Game/Logic/Object/Body/BodyModule.cs
This can change when the Hold The Line battleplan is activated or deactivated
=> Parse BodyModule armorDamageScalar

src/OpenSage.Game/Logic/Object/Create/SpecialPowerCreate.cs
Missed this the first time around
=> Add missing SpecialPowerCreate persister

src/OpenSage.Game/Gui/CommandButtonCallback.cs, src/OpenSage.Game/Logic/AI/AIStateMachine.cs, src/OpenSage.Game/Logic/AI/AIStates/HackInternetState.cs, src/OpenSage.Game/Logic/AI/AIStates/StartHackingInternetState.cs, src/OpenSage.Game/Logic/AI/AIStates/StopHackingInternetState.cs, src/OpenSage.Game/Logic/AI/StateMachineBase.cs, src/OpenSage.Game/Logic/Object/UnitSpecificSounds.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/AIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/HackInternetAIUpdate.cs, src/OpenSage.Game/Logic/Orders/OrderProcessor.cs
This implements hack internet for the most part. Pack/unpack animations still need to be scaled, and I haven't been able to fully parse out the pack data object. We'll also need to property implement the state machines in order to handle transitions, e.g. from hacking to entering a building/vehicle 
scaling animation time is not yet implemented
=> Implement HackInternetAIUpdate

src/OpenSage.Game/Audio/MiscAudio.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Upgrade/ExperienceScalarUpgrade.cs, src/OpenSage.Mods.Generals/GeneralsScene25D.cs
=> Level up unit at requisite experience intervals

src/OpenSage.Game/Logic/Object/ClientUpdate/LaserUpdate.cs, src/OpenSage.Game/Logic/Object/Draw/W3dLaserDraw.cs, src/OpenSage.Game/Logic/Object/SpecialPower/SpecialPower.cs, src/OpenSage.Game/Logic/Object/Update/FireWeaponUpdate.cs, src/OpenSage.Game/Logic/Object/Update/ParticleUplinkCannonUpdate.cs
=> Parse modules used in particle cannon

src/OpenSage.Game/Logic/Object/Update/AIUpdate/DeployStyleAIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/HackInternetAIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/JetAIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/UnknownStateData.cs
This seems to have something to do with a queued state of sorts, but I'm not clear exactly what its purpose is yet.
=> Consolidate common AIUpdate data object

src/OpenSage.Game/Gui/InGame/InGameUI.cs, src/OpenSage.Game/Logic/Object/Update/FireWeaponUpdate.cs, src/OpenSage.Game/Logic/Object/Update/ProductionExit/QueueProductionExitUpdate.cs, src/OpenSage.Game/Scripting/ScriptingSystem.cs
Names a few sav file fields found while investigating superweapons
=> Superweapon sav parsing

src/OpenSage.Game/Client/Drawable.cs, src/OpenSage.Game/Graphics/ModelInstance.cs, src/OpenSage.Game/Logic/Object/Draw/W3dModelDraw.cs
=> Fix subobjects not hiding their bones

src/OpenSage.Game/Client/Drawable.cs, src/OpenSage.Game/Graphics/Animation/AnimationInstance.cs, src/OpenSage.Game/Logic/Object/Draw/DrawModule.cs, src/OpenSage.Game/Logic/Object/Draw/W3dModelDraw.cs, src/OpenSage.Game/Logic/Object/Draw/W3dSupplyDraw.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/HackInternetAIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/SupplyWarehouseDockUpdate.cs, src/OpenSage.Game/Logic/Player.cs, src/OpenSage.Game/Scene3D.cs, src/OpenSage.Launcher/Program.cs
#875 implemented `HackInternetAIUpdate`, but it didn't implement scaling the unpacking / packing animations based on the randomized duration. This PR implements that.
=> Implement animation duration scaling for hacker unpacking / packing

src/OpenSage.Game/Logic/Object/GameObject.cs
=> Deselect selected unit on death

src/OpenSage.Game/Content/ContentManager.cs, src/OpenSage.Game/Content/SubsystemLoader.cs, src/OpenSage.Game/Logic/Object/ArmorTemplate.cs, src/OpenSage.Game/Subsystem.cs
=> Load Armor subsystem

src/OpenSage.Game/Logic/AI/AIStateMachine.cs, src/OpenSage.Game/Logic/AI/AIStates/WaitForAirfieldState.cs
Came across this for a raptor that was orbiting out of ammo with no airfield to land at.
=> Add state machine state for winchester aircraft looking for airfield

src/OpenSage.Game.Tests/Gui/Apt/ActionScript/InstructionParsingTest.cs, src/OpenSage.Game.Tests/Mathematics/AngleTests.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/JetAIUpdate.cs, src/OpenSage.Game/Utilities/StructInteropUtility.cs, src/OpenSage.IO/SearchPattern.cs, src/OpenSage.Launcher/Program.cs, src/OpenSage.Mods.Generals/GeneralsScene25D.cs
Fixes build warnings which are not CS8632
=> Fix build warnings

src/OpenSage.Game/Client/Drawable.cs, src/OpenSage.Game/Graphics/ParticleSystems/ParticleSystem.cs, src/OpenSage.Game/Gui/InGame/InGameUI.cs, src/OpenSage.Game/Logic/AI/AIStateMachine.cs, src/OpenSage.Game/Logic/GameLogic.cs, src/OpenSage.Game/Logic/Object/Behaviors/GenerateMinefieldBehavior.cs, src/OpenSage.Game/Logic/Object/Body/ActiveBody.cs, src/OpenSage.Game/Logic/Object/Contain/OpenContain.cs, src/OpenSage.Game/Logic/Object/Damage/DamageData.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Helpers/StatusDamageHelper.cs, src/OpenSage.Game/Logic/Object/Helpers/SubdualDamageHelper.cs, src/OpenSage.Game/Logic/Object/Helpers/TempWeaponBonusHelper.cs, src/OpenSage.Game/Logic/Object/ObjectStatus.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/DeployStyleAIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/UnknownStateData.cs, src/OpenSage.Game/Logic/Object/Update/FireWeaponUpdate.cs, src/OpenSage.Game/Logic/Object/Update/OCLUpdate.cs, src/OpenSage.Game/Logic/Object/Update/StealthUpdate.cs, src/OpenSage.Game/Logic/Object/Upgrade/ArmorUpgrade.cs, src/OpenSage.Game/Logic/Object/Weapon/WeaponSet.cs, src/OpenSage.Game/Logic/Player.cs, src/OpenSage.Game/Network/SkirmishGameSettings.cs, src/OpenSage.Game/Scripting/ScriptGroup.cs, src/OpenSage.Game/Terrain/TerrainVisual.cs
I wanted to be able to open Zero Hour `.sav` files, but I found a few missing bits and pieces. This PR implements enough things to be able to open simple `.sav` files with a small selection of objects.
=> Implement .sav parsing for Zero Hour

src/OpenSage.Game/Game.cs, src/OpenSage.Game/Gui/Wnd/WndInputMessageHandler.cs, src/OpenSage.Game/Input/Cursors/CursorManager.cs, src/OpenSage.Game/Logic/Player.cs
=> Made cursor always be Arrow when over a WND element

NuGet.config, src/Directory.Build.props, src/Directory.Packages.props, src/OpenSage.Benchmarks.DataStructures/OpenSage.Benchmarks.DataStructures.csproj, src/OpenSage.Core/OpenSage.Core.csproj, src/OpenSage.FileFormats/OpenSage.FileFormats.csproj, src/OpenSage.Game.CodeGen/OpenSage.Game.CodeGen.csproj, src/OpenSage.Game.Tests/OpenSage.Game.Tests.csproj, src/OpenSage.Game/OpenSage.Game.csproj, src/OpenSage.Launcher/OpenSage.Launcher.csproj, src/OpenSage.Mathematics.Tests/OpenSage.Mathematics.Tests.csproj, src/OpenSage.Rendering/OpenSage.Rendering.csproj, src/OpenSage.Tools.BigEditor/OpenSage.Tools.BigEditor.csproj, src/OpenSage.Tools.BigTool/OpenSage.Tools.BigTool.csproj, src/OpenSage.Tools.Sav2Json/OpenSage.Tools.Sav2Json.csproj
[Central package management](https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management) is the modern way to manage package versions. Let's use it.
=> Use central package management

src/OpenSage.Game.Tests/Logic/Object/Behaviors/AutoHealBehaviorTests.cs, src/OpenSage.Game.Tests/Logic/Object/Upgrade/UpgradeLogicTests.cs, src/OpenSage.Game.Tests/Logic/Object/Upgrade/UpgradeModuleTest.cs, src/OpenSage.Game/Logic/Object/Behaviors/AutoHealBehavior.cs, src/OpenSage.Game/Logic/Object/Upgrade/UpgradeModule.cs
This also adds some basic UpgradeLogic tests as I needed to support that anyway.
=> Add persister tests for AutoHealBehavior

src/OpenSage.Game.Tests/Logic/Object/BehaviorModuleTest.cs, src/OpenSage.Game.Tests/Logic/Object/Behaviors/PhysicsBehaviorTests.cs, src/OpenSage.Game.Tests/StatePersisterTest.cs, src/OpenSage.Game/Data/Map/HeightMapData.cs, src/OpenSage.Game/Data/Map/Player.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/GameContext.cs, src/OpenSage.Game/IGame.cs, src/OpenSage.Game/Logic/Object/Behaviors/PhysicsBehavior.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/ObjectDefinition.cs, src/OpenSage.Game/Logic/OrderGenerators/OrderGenerator.cs, src/OpenSage.Game/Logic/Player.cs, src/OpenSage.Game/Logic/PlayerManager.cs, src/OpenSage.Game/Scene3D.cs, src/OpenSage.Game/Terrain/Terrain.cs, src/OpenSage.Game/Terrain/TerrainLogic.cs
I don't love the things I had to do add this test 😄 But the test itself is _roughly_ the kind of thing I'd like to write.
=> Add PhysicsBehavior.Update test

src/OpenSage.Game.Tests/Logic/Object/Behaviors/FireWeaponWhenDeadBehaviorTests.cs, src/OpenSage.Game/Data/Ini/IniParseTable.cs, src/OpenSage.Game/Logic/Object/Behaviors/FireWeaponWhenDeadBehavior.cs, src/OpenSage.Game/Logic/Object/Behaviors/InstantDeathBehavior.cs, src/OpenSage.Game/Logic/Object/Behaviors/SlowDeathBehavior.cs, src/OpenSage.Game/Logic/Object/Die/CreateObjectDie.cs, src/OpenSage.Game/Logic/Object/Die/DestroyDie.cs, src/OpenSage.Game/Logic/Object/Die/DieModule.cs, src/OpenSage.Game/Logic/Object/Die/EjectPilotDie.cs, src/OpenSage.Game/Logic/Object/Die/FXListDie.cs, src/OpenSage.Game/Logic/Object/Die/KeepObjectDie.cs, src/OpenSage.Game/Logic/Object/Die/RebuildHoleExposeDie.cs, src/OpenSage.Game/Logic/Object/Die/UpgradeDie.cs, src/OpenSage.Game/Logic/Object/ObjectStatus.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/MissileAIUpdate.cs
=> Implement FireWeaponWhenDeadBehavior

src/OpenSage.Game.Tests/Logic/Object/Behaviors/ParkingPlaceBehaviorTests.cs, src/OpenSage.Game/Logic/Object/Behaviors/ParkingPlaceBehavior.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/JetAIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/ProductionUpdate.cs, src/OpenSage.Game/StatePersister.cs
#983
All bytes of ParkingPlaceBehavior in Generals are now fully parsed. Zero Hour hasn't been tested yet.
Aircraft still have a bit to go before we get them properly working - namely JetAIUpdate (#986) needs some progress. I've parsed out a lot of the jet AI states as well, but those will come in a separate PR.
This PR aims to provide backwards compatibility with the existing aircraft code to an extent. I'll be addressing that functionality in the future as well as we move to the JetAIUpdate states.
=> Update ParkingPlaceBehavior and add tests

src/OpenSage.Game.Tests/Logic/Object/Update/JetAIUpdateTests.cs, src/OpenSage.Game.Tests/MockedGameTest.cs, src/OpenSage.Game.Tests/StatePersisterTest.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/AIUpdate.cs
This caused Generals to instantly crash in the main menu, but it works after the change.
=> Fix incorrect virtual property access in constructor in AIUpdate.cs

src/OpenSage.Game/Client/Drawable.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/Logic/Object/ClientUpdate/ClientUpdate.cs, src/OpenSage.Game/Logic/Object/ClientUpdate/SwayClientUpdate.cs, src/OpenSage.Game/Logic/Object/Draw/DrawModule.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/ModuleBase.cs, src/OpenSage.Game/Scripting/ScriptingSystem.cs
Before, trees didn't sway.
Now, trees sway:
https://github.com/user-attachments/assets/a3726d39-86f2-4b42-9c3e-bcbe8a188ffc
Resolves #1314.
=> Port SwayClientUpdate from Generals

src/OpenSage.Game/Client/Drawable.cs, src/OpenSage.Game/Logic/AI/Pathfinder.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Update/ToppleUpdate.cs, src/OpenSage.Game/Scripting/ScriptingSystem.cs, src/OpenSage.Mathematics/Percentage.cs
Before: no bouncing.
After:
https://github.com/user-attachments/assets/68f6622a-0d76-421e-96e1-12c49a77f96f
Note that the particle system used for BounceFX is not rendered correctly - it looks like there's a problem with its transparency. But that's a separate issue.
Resolves #1216.
=> Port ToppleUpdate from Generals

src/OpenSage.Game.Tests/MockedGameTest.cs, src/OpenSage.Game/Diagnostics/RenderedView.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/GameEngine.cs, src/OpenSage.Game/Graphics/ParticleSystems/ParticleSystemManager.cs, src/OpenSage.Game/Graphics/Rendering/RenderContext.cs, src/OpenSage.Game/Graphics/Rendering/RenderPipeline.cs, src/OpenSage.Game/Graphics/Rendering/Shadows/ShadowMapRenderer.cs, src/OpenSage.Game/Graphics/Rendering/Water/WaterMapRenderer.cs, src/OpenSage.Game/Gui/DebugUI/DebugOverlay.cs, src/OpenSage.Game/IGame.cs, src/OpenSage.Game/IGameDefinition.cs, src/OpenSage.Game/IScene3D.cs, src/OpenSage.Game/Logic/OrderGenerators/ConstructBuildingOrderGenerator.cs, src/OpenSage.Game/Logic/OrderGenerators/IOrderGenerator.cs, src/OpenSage.Game/Logic/OrderGenerators/OrderGenerator.cs, src/OpenSage.Game/Logic/OrderGenerators/RallyPointOrderGenerator.cs, src/OpenSage.Game/Logic/OrderGenerators/SpecialPowerOrderGenerator.cs, src/OpenSage.Game/Logic/OrderGenerators/UnitOrderGenerator.cs, src/OpenSage.Game/Scene25D.cs, src/OpenSage.Game/Scene3D.cs, src/OpenSage.Game/Scripting/ScriptExecutionContext.cs, src/OpenSage.Mods.Bfme/BfmeDefinition.cs, src/OpenSage.Mods.Bfme2/Bfme2Definition.cs, src/OpenSage.Mods.Bfme2/Bfme2RotwkDefinition.cs, src/OpenSage.Mods.Generals/GeneralsDefinition.cs, src/OpenSage.Mods.Generals/GeneralsScene25D.cs, src/OpenSage.Mods.Generals/GeneralsZeroHourDefinition.cs
=> Replace usages of Scene3D with IScene3D

src/OpenSage.Game/Data/Map/UserMapCache.cs
Based on https://github.com/electronicarts/CnC_Generals_Zero_Hour/blob/0a05454d8574207440a5fb15241b98ad0b435590/Generals/Code/GameEngine/Source/Common/crc.cpp#L55
=> chore: implement crc calculation for maps

src/OpenSage.Game.Tests/Logic/Object/Behaviors/PhysicsBehaviorTests.cs, src/OpenSage.Game/Client/Drawable.cs, src/OpenSage.Game/Entity.cs, src/OpenSage.Game/Logic/Object/Animation.cs, src/OpenSage.Game/Logic/Object/Behaviors/PhysicsBehavior.cs, src/OpenSage.Game/Logic/Object/Geometry.cs, src/OpenSage.Game/Logic/Object/Locomotor.cs, src/OpenSage.Game/Logic/Object/LocomotorTemplate.cs, src/OpenSage.Game/Logic/Object/ObjectDefinition.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/AIUpdate.cs
https://github.com/user-attachments/assets/9cc38342-eef7-40f1-a8dc-68f0ff5b6c44
TODO:
*Edit*: Actually I'll do the above two things in separate PRs. I'm having trouble understanding how to apply deltaTime to this drawable locomotor stuff, so I first want to refactor some of the client / logic timing code.
=> Port locomotor-related code in Drawable
