OpenSAGE/OpenSAGE

src/OpenSage.DataViewer.Windows/Bootstrapper.cs, src/OpenSage.DataViewer/ViewModels/ShellViewModel.cs, src/OpenSage.Game.Tests/Big/BigArchiveTests.cs, src/OpenSage.Game.Tests/InstalledFilesTestData.cs, src/OpenSage.Game.Tests/W3d/W3dFileTests.cs, src/OpenSage.Game/Data/Ini/AddedInAttribute.cs, src/OpenSage.Game/Data/InstallationLocator.cs, src/OpenSage.Game/SageGame.cs
This is a work in progress implementation of a registry-based installation folder resolver, as mentioned in #4. The core feature is functional, and I'm now able to run the data viewer on my computer and access the data from Origin copies of Generals & Zero Hour. There is still some work to be done - see the checklist below and the self-review comments.
=> WIP: Resolve game installation paths from Windows registry

src/OpenSage.DataViewer.Windows/App.xaml.cs, src/OpenSage.Game/Data/Ini/Parser/IniLexer.cs, src/OpenSage.Game/Data/Utilities/ParseUtility.cs, src/OpenSage.Game/Data/W3d/W3dVertexMapperArgs.cs
`float.Parse` uses the current locale setting of the OS to decide which floating point format to use. This is a problem in countries which use the [decimal comma](https://en.wikipedia.org/wiki/Decimal_mark#Countries_using_Arabic_numerals_with_decimal_comma) (which include the vast majority of European and South American countries).
This PR fixes that issue by making `InvariantCulture` (basically `en-us`) the default culture for the main thread and newly created threads.
=> Fix floating point parsing on non-English Windows

src/OpenSage.DataViewer/UI/ContentView.cs, src/OpenSage.DataViewer/UI/Viewers/ConstViewer.cs, src/OpenSage.Game.Tests/Apt/ConstFileTests.cs, src/OpenSage.Game/Data/Apt/ConstantData.cs, src/OpenSage.Game/Data/Utilities/Extensions/BinaryReaderExtensions.cs
The .const file format is the first step towards the integration of BFME (and following) GUI file formats. The file contains all constant variables that can be accessed by the correcsponding ,apt file in ActionScript and by Characters.
As an example it defines TextColors as a hexadecimal number.
=> Added the .const file format

src/OpenSage.Game/Data/Ini/Parser/IniParser.cs, src/OpenSage.Game/Data/Wnd/WndFile.cs, src/OpenSage.Game/Gui/Elements/UIElement.cs
(Based on #13)
Treat UI elements with null HeaderTemplate like ones set to "[NONE]"
Fixes crashes when viewing certain UI controls in the data viewer, such as the MOTD.
=> Fix controls with null header template

src/OpenSage.Game/Data/InstallationLocator.cs
When installing an Origin copy of the Generals + Zero Hour bundle on my secondary workstation I found out that for some reason it uses a different registry key than my other computer for ZH. No idea why.
Since the alternative registry key requires some special handling, I implemented it and decided to move Zero Hour installation resolution to a different method entirely. As a bonus, a Generals installation is only resolved once for all possible Zero Hour installations.
=> Add support for special registry key for Zero Hour, refactor installation location

src/OpenSage.Game.Tests/Apt/AptFileTest.cs, src/OpenSage.Game.Tests/Apt/ConstFileTests.cs, src/OpenSage.Game.Tests/Big/BigArchiveTests.cs, src/OpenSage.Game.Tests/GameTestDiscoverer.cs, src/OpenSage.Game/Data/InstallationLocator.cs
(Based on #15)
This PR implements a custom XUnit test discoverer, which filters the tests by the games you have installed. Tests that require a specific game can be tagged with `[GameFact(SageGame.GameName)]`. I haven't classified every test yet, but I can do that if required.
The motivation behind this is that it doesn't make much sense to run tests that couldn't possibly pass because of missing data files. It also documents in a neat, declarative way which tests require which games.
=> Skip tests for games you don't have installed

src/OpenSage.Game/Game.cs, src/OpenSage.Game/GameSystem.cs
Fixes #19 .
`OnSceneChange` is virtual so that systems can customise the behaviour it if necessary.
=> Clear game systems' component lists on scene change

src/OpenSage.Game/Content/MapLoader.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/GameSystem.cs
Fixes map object Z positioning by _adding_ the height map value at current position to the object's Z position instead of ignoring it entirely.
Before: 
After:
WorldBuilder for reference:
=> Fix map object z positioning

src/OpenSage.Game/Data/Ini/Parser/IniParser.cs
Fixes test `IniFileTests.CanReadIniFiles` for languages that don't use the decimal point.
=> Fix IniParser.IsFloat on non-English Windows

src/OpenSage.Game.Tests/GameTestDiscoverer.cs, src/OpenSage.Game/Content/MapLoader.cs, src/OpenSage.Game/Data/InstallationLocator.cs, src/OpenSage.Game/Scripting/Actions/MoveCameraAlongWaypointPathAction.cs, src/OpenSage.Game/Settings/SceneSettings.cs, src/OpenSage.Game/Terrain/HeightMap.cs, src/OpenSage.Game/Utilities/Extensions/EnumerableExtensions.cs
Fixes #22, fixes #27.
Fixes a number of campaign maps. Every map in the China campaign loads except for `CHI03`.
* Check if the coordinate is within bounds in `HeightMap.GetHeight`, return 0 if not.
* Parse `wayPointPathLabel` properties and store them in `Settings.Waypoint`s.
* Implement `WaypointPathCollection` which allows looking up `WaypointPath`s by their first node and their label.
* Fix `MoveCameraAlongWaypointPathAction`.
* As a bonus, add two self-explanatory LINQ extensions: `WhereNot` and `ToSet`. Not absolutely necessary, but I though they'd be useful.
=> Map loading fixes

src/OpenSage.Game.Tests/OpenSage.Game.Tests.csproj
This change is necessary, because the tests aren't properly detected or run, in some instances (including my machine). By updating the NuGet Packages everything is working again as expected
=> Updated Nuget packages for Xunit and the Test SDK

src/OpenSage.Game/Gui/Wnd/Transitions/ReverseSoundTransition.cs, src/OpenSage.Game/Gui/Wnd/Transitions/WinScaleUpTransition.cs, src/OpenSage.Game/Gui/Wnd/Transitions/WindowTransitionOperation.cs, src/OpenSage.Game/Gui/Wnd/WndInputMessageHandler.cs, src/OpenSage.Game/Gui/Wnd/WndTopLevelWindow.cs, src/OpenSage.Game/Gui/Wnd/WndWindowManager.cs, src/OpenSage.Mods.Generals/WndCallbacks.cs
* Implement enough UI callbacks to open all subsections of the main menu (except for credits)
* Ignore click events when a component is not fully opaque
* Add stub implementations for `ReverseSoundTransition` and `WinScaleUpTransition`
* Add ESC as a hotkey for closing the topmost window. Entirely optional, can be left out if it causes issues.
=> Implement more wnd callbacks for Generals' main menu + close windows with ESC

src/OpenSage.DataViewer/UI/Viewers/Ini/ParticleSystemView.cs, src/OpenSage.Game/Data/Ini/ParticleSystem.cs, src/OpenSage.Game/Graphics/ParticleSystems/Particle.cs, src/OpenSage.Game/Graphics/ParticleSystems/ParticleSystem.cs, src/OpenSage.Game/Graphics/ParticleSystems/ParticleSystemSystem.cs, src/OpenSage.Game/Logic/Object/Draw/W3dModelDraw.cs, src/OpenSage.Game/Mathematics/Vector3Utility.cs
* Change `ParticleAlphaKeyframe` and `ParticleColorKeyframe` into structs to reduce allocations during rendering.
* Reuse alpha keyframe lists
* Extract the logic for finding the current and previous keyframes into a separate function
* Reduce large struct copies by adding `in` to `Vector3` arguments and passing world matrices by a readonly reference.
* Note that Vector3 copies can't be completely eliminated, because `System.Numerics` doesn't use `in` parameters yet.
* Fix engine crash when trying to initialize particle systems with burst count of 0. Fixed by adding an early return to `ParticleSystem` constructor, and null checks in `Update` and `BuildRenderList`.
With this patch particle systems should allocate **0 bytes** after initialisation.
=> Optimize particle systems

NuGet.config, src/OpenSage.Game/Configuration.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/GameFactory.cs, src/OpenSage.Game/Gui/Apt/AptMainMenuSource.cs, src/OpenSage.Game/Gui/IMainMenuSource.cs, src/OpenSage.Game/Gui/Wnd/WndMainMenuSource.cs, src/OpenSage.Game/Gui/Wnd/WndWindow.cs, src/OpenSage.Game/IGameDefinition.cs, src/OpenSage.Launcher/OpenSage.Launcher.csproj, src/OpenSage.Launcher/Program.cs, src/OpenSage.Mods.Bfme/BfmeDefinition.cs, src/OpenSage.Mods.BfmeII/BfmeIIDefinition.cs, src/OpenSage.Mods.BuiltIn/GameDefinition.cs, src/OpenSage.Mods.Cnc3/Cnc3Definition.cs, src/OpenSage.Mods.Cnc3/Cnc3KanesWrathDefinition.cs, src/OpenSage.Mods.Cnc4/Cnc4Definition.cs, src/OpenSage.Mods.Generals/GeneralsDefinition.cs, src/OpenSage.Mods.Generals/GeneralsZeroHourDefinition.cs, src/OpenSage.Mods.Generals/WndCallbacks.cs, src/OpenSage.Mods.Ra3/Ra3Definition.cs, src/OpenSage.Mods.Ra3/Ra3UprisingDefinition.cs
* `--noshellmap`
* Skips loading the shell map, speeding up initial loading time.
* Present in SAGE, but with only one dash.
* Related to this: draw the static background image in Generals & ZH main menu if there's no 3D scene.
* `--game`
* Chooses which game to start. Generals is still the default.
* Currently takes the game name as a case-insensitive `SageGame` entry. I'd like to replace this with a shorter string identifier (added to `IGameDefinition`), which could be used for other things such as configuration files, debug information and maybe even multiplayer lobbies.
* Add `IMainMenuSource`, `WndMainMenuSource` and `AptMainMenuSource`
* Add `Configuration` type. The only implemented setting right now is `bool LoadShellMap`.
* Add a reference to `IGameDefinition` in `Game`
* Move …
=> Add basic launch parameters to launcher using System.CommandLine

src/OpenSage.Launcher/OpenSage.Launcher.csproj
…and explicitly set PlatformTarget to x64 to avoid BadImageFormatException (as x86 is the implicit default for SDK-based netfx projects)
=> [launcher] Fix soft_oal.dll not being copied to the output directory

src/OpenSage.DataViewer/UI/Viewers/Ini/ObjectDefinitionView.cs, src/OpenSage.DataViewer/UI/Viewers/Ini/ParticleSystemView.cs, src/OpenSage.DataViewer/UI/Viewers/W3dView.cs, src/OpenSage.Game/Content/MapLoader.cs, src/OpenSage.Game/Content/Util/ConversionExtensions.cs, src/OpenSage.Game/Data/Map/AssetPropertyCollection.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/Graphics/Util/ConversionExtensions.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/GameObjectCollection.cs, src/OpenSage.Game/Logic/Player.cs, src/OpenSage.Game/Mathematics/ColorRgb.cs, src/OpenSage.Game/Scene3D.cs
Do not merge yet.
* Adds `Team` and parses them from the map file. A team is a group of objects owned by a player.
* Parses `Player`s from the map file.
* Expands `Player` with new properties, including allies and enemies.
* Adds `Owner` and `Health` to `GameObject`. These are now parsed from the `MapObject`.
* Adds an overload to `GameObjectCollection.Add` which takes a `GameObject`.
=> Add team class, improve map loading

src/OpenSage.Game/Graphics/Cameras/CameraInputMessageHandler.cs, src/OpenSage.Game/Gui/Wnd/WndInputMessageHandler.cs, src/OpenSage.Game/Gui/Wnd/WndWindowManager.cs, src/OpenSage.Game/Input/HandlingPriority.cs, src/OpenSage.Game/Input/InputMessageBuffer.cs, src/OpenSage.Game/Input/InputMessageHandler.cs, src/OpenSage.Game/Logic/SelectionMessageHandler.cs, src/OpenSage.Game/Logic/SelectionSystem.cs, src/OpenSage.Game/Scene3D.cs
* Go through `InputMessageHandler`s in the priority order instead of registration order. This uses the `HandlingPriority` enum and the abstract `Priority` property in `InputMessageHandler`. The algorithm is implemented as an iterator: for each message, the handlers are looped through starting with the highest possible priority. If there is a handler matching the priority level, yield it. Decrease the priority threshold by one, and go through the handlers again.
* Prioritise selection system over UI when a selection box is being dragged
* Prioritise camera system over UI when the camera is being moved or rotated.
* Consume right click and middle click events when the cursor is over a control.
=> Input handler priority

src/OpenSage.Game/Content/ContentManager.cs, src/OpenSage.Game/Data/Ini/ControlBarScheme.cs, src/OpenSage.Game/Data/Ini/Parser/IniParser.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/Gui/IControlBar.cs, src/OpenSage.Game/Gui/Wnd/Controls/Window.cs, src/OpenSage.Game/Gui/Wnd/Images/MappedImageLoader.cs, src/OpenSage.Game/Gui/Wnd/Images/WndImageLoader.cs, src/OpenSage.Game/Gui/Wnd/WndControlBar.cs, src/OpenSage.Game/Gui/Wnd/WndInputMessageHandler.cs, src/OpenSage.Game/IGameDefinition.cs, src/OpenSage.Game/Mathematics/Point2D.cs, src/OpenSage.Game/Mathematics/Rectangle.cs, src/OpenSage.Game/Scene2D.cs, src/OpenSage.Mods.Bfme/BfmeDefinition.cs, src/OpenSage.Mods.Bfme2/Bfme2Definition.cs, src/OpenSage.Mods.Bfme2/Bfme2RotwkDefinition.cs, src/OpenSage.Mods.Cnc3/Cnc3Definition.cs, src/OpenSage.Mods.Cnc3/Cnc3KanesWrathDefinition.cs, src/OpenSage.Mods.Cnc4/Cnc4Definition.cs, src/OpenSage.Mods.Generals/GeneralsDefinition.cs, src/OpenSage.Mods.Generals/GeneralsZeroHourDefinition.cs, src/OpenSage.Mods.Generals/Gui/ControlBarCallbacks.cs, src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs, src/OpenSage.Mods.Generals/Gui/QuitMenuCallbacks.cs, src/OpenSage.Mods.Ra3/Ra3Definition.cs, src/OpenSage.Mods.Ra3/Ra3UprisingDefinition.cs
* Implement control bar abstraction, with `IControlBar` and `IControlBarSource`.
* Move control bar to its own classes
* Apply the control bar theme from `ControlBarScheme.ini`
* Remove ESC as a window-closing hotkey. The exact reasons are outlined in 5b05fd95b1b2d20835322d59587a95d2df7ce877, but the gist of it is that it was a hack from the start, and it's not going to work properly outside of the main menu.
* **Bonus!** Fix starting building / unit positions.
=> Controlbar improvements

src/OpenSage.Game.Tests/Data/InstalledFilesTestData.cs, src/OpenSage.Game/Content/TextureLoader.cs, src/OpenSage.Game/Data/FileSystem.cs, src/OpenSage.Game/Data/Ini/ChallengeGenerals.cs, src/OpenSage.Game/Data/Ini/ObjectFilter.cs, src/OpenSage.Game/Data/Ini/Parser/IniParser.Enums.cs, src/OpenSage.Game/Data/Ini/Parser/IniParser.cs, src/OpenSage.Game/Data/Ini/Weapon.cs, src/OpenSage.Game/Data/InstallationLocator.cs, src/OpenSage.Viewer/UI/ContentView.cs
Fixes issues with Turkish locale. This was just a find-and-replace job - some calls could work just fine without these changes, but it's good to be consistent.
=> Use the Invariant version of ToUpper and ToLower (and fix Turkish locale)

src/Directory.Build.props, src/OpenSage.Game/GameWindow.cs, src/OpenSage.Game/Graphics/Rendering/RenderPipeline.cs, src/OpenSage.Game/Graphics/Shaders/FixedFunction.cs, src/OpenSage.Game/Graphics/Shaders/NormalMapped.cs, src/OpenSage.Game/Graphics/Shaders/Particle.cs, src/OpenSage.Game/Graphics/Shaders/Simple.cs, src/OpenSage.Game/Graphics/Shaders/Terrain.cs, src/OpenSage.Game/OpenSage.Game.csproj, src/OpenSage.Launcher/OpenSage.Launcher.csproj, src/OpenSage.Viewer/Framework/ImGuiGamePanel.cs, src/OpenSage.Viewer/OpenSage.Viewer.csproj, src/OpenSage.Viewer/Program.cs, src/OpenSage.Viewer/UI/Views/GameView.cs
The updating is required because ShaderGen was producing invalid shaders for cultures that use ',' as float seperator
=> Update veldrid and shadergen

src/OpenSage.Launcher/Program.cs, src/OpenSage.Viewer/UI/MainForm.cs
Fixes #127.
Launcher:
Viewer:
The link in the viewer [should work](https://github.com/dotnet/corefx/pull/23705) on Mac and Linux, but I haven't tried it yet.
=> Show a message when no games are detected

src/OpenSage.Game/Graphics/Cameras/CameraComponent.cs
The near clipping plane value was way too low, meaning that the depth buffer did not have enough precision to handle rendering everything correctly. Upping it to `4.0f` makes no discernible difference in gameplay; the only difference is if you zoom in very very close to a unit (to the point where you are almost on top of it), you may see the near polygons clipped. However you are never allowed to zoom in that far in practice. Here is what the `USA02.map` stadium looks like now:
=> Resolve z fighting issues: Fixes #106

src/OpenSage.Game/OpenSage.Game.csproj
I recgnized a bug in the linux version of OpenSAGE. 
> Unhandled Exception: System.MissingMethodException: Method not found: 'System.Span`1<!!1> System.MemoryExtensions.NonPortableCast(System.Span`1<SixLabors.ImageSharp.PixelFormats.Rgba32>)'.
at SixLabors.ImageSharp.Image.LoadPixelData[TPixel](Configuration config, Byte[] data, Int32 width, Int32 height)
at OpenSage.Content.TextureLoader.CreateTextureFromTga(GraphicsDevice graphicsDevice, TgaFile tgaFile, Boolean generateMipMaps) in /home/patrick/Workspace/OpenSAGE/src/OpenSage.Game/Content/TextureLoader.cs:line 93
at OpenSage.Content.TextureLoader.LoadEntry(FileSystemEntry entry, ContentManager contentManager, Game game, LoadOptions loadOptions) in /home/patrick/Workspace/OpenSAGE/src/OpenSage.Game/Content/TextureLoader.cs:line 62
at …
=> Increase ImageSharp version to beta 4

src/OpenSage.Game/Audio/AudioBuffer.cs, src/OpenSage.Game/Data/Wav/WavFile.cs, src/OpenSage.Launcher/Program.cs
Some C&C Generals sounds are stored in a compressed format known as DVI (or IMA) ADPCM. One such example is `Data\Audio\Sounds\ctrustaa.wav`, which would previously cause a crash in the viewer when played. Since OpenAL does not support the format, we implement an on-the-fly decoder to unpack the compression into a linear PCM format that OpenAL can play. Note this commit only supports single channel files of this type, although supporting multiple channels should not be too hard (I haven't found any of these types of sounds yet though).
Uses
https://icculus.org/SDL_sound/downloads/external_documentation/wavecomp.htm
https://wiki.multimedia.cx/index.php/IMA_ADPCM
as references.
=> Support for mono DVI ADPCM compressed .wav files

src/OpenSage.Launcher/OpenSage.Launcher.csproj, src/OpenSage.Launcher/Program.cs, src/OpenSage.Viewer/OpenSage.Viewer.csproj, src/OpenSage.Viewer/Program.cs
The commandline parser we used previously was declared as "System.Commandline" parser, but was actually a private project (see [here](https://www.nuget.org/packages/System.CommandLine/1.0.0.4)). The project is still available [here](https://github.com/deniszykov/commandline).
Instead of changing to the new repository i decided to switch to the much more used commandline parser. It has a much nicer api and allows short/long options etc. It can directly parse Enums from the arguments. Overall i think it's the better choice for future development.
=> Replace commandline parser

src/OpenSage.Game.Tests/Data/Tga/TgaFileTests.cs
Skip "map ang rhudaur.tga" in unit-tests. This file is not referenced in any ini file of the rise of the witch king expansion and seems to be corrupted, since the image width is negative and the image type is 82, which is not mentioned in any documentation of the tga file format.
=> skip unreferenced tga file in rise of the witch king

src/OpenSage.Viewer/UI/MainForm.cs, src/OpenSage.Viewer/UI/Views/GameView.cs, src/OpenSage.Viewer/UI/Views/IniView.cs
* Don't draw the game view when there's not enough space. Fixes a crash when the viewer window is really small.
* Implement a text view for INI files.
* This currently uses a normal unformatted text control. This means the text cannot be highlighted or copied. We'll migrate to a readonly multiline input when ImGui.NET has solved [this issue](https://github.com/mellinoe/ImGui.NET/issues/82).
* Show a notification when a game view has input focus
* Add a context menu option to copy INI contents to clipboard.
* Default to text view when the file doesn't contain any known objects (and hide the view selector).
=> Viewer improvements

src/OpenSage.Game/Content/ContentManager.cs, src/OpenSage.Game/Content/SubsystemLoader.cs, src/OpenSage.Game/Data/Ini/LoadSubsystem.cs, src/OpenSage.Game/Subsystem.cs
* Implement rudimentary subsystem support. Subsystems are a concept in BFME and newer games, which are used to load related configuration files.
* Tweak `LoadSubsystem` parsing to be order-preserving
This PR doesn't integrate subsystems properly into the engine yet. Most subsystems are immediately loaded in `ContentManager` and most manual INI loading calls still remain. Not every subsystem has been added yet, and I've only looked at BFME2 and C&C3 so far.
=> Subsystems

src/OpenSage.Game.Tests/Data/Map/MapFileTests.cs, src/OpenSage.Game/Content/MapLoader.cs, src/OpenSage.Game/Data/Map/BlendTileData.cs, src/OpenSage.Game/Data/Utilities/Extensions/BinaryReaderExtensions.cs, src/OpenSage.Game/Data/Utilities/Extensions/BinaryWriterExtensions.cs
I figured what the previous `Unknown` bytes were for. The `Blends`, `ThreeWayBlends`, and `CliffTextures` data seems to be 32-bit between versions 14 and 24. And then after version 24, oddly, went back to 16-bit.
=> Fix tile blending in BFME

src/OpenSage.Game.Tests/Data/W3d/W3dFileTests.cs, src/OpenSage.Game/Data/W3d/W3dMaterialPass.cs
Parse shader material ids. Skip file "readonly-0-rev-2-lwbanhwitchk.w3d" in unit tests, since it is corrupted and not referenced by any ini file.
=> Parse shader material ids, skip corrupted and unreferenced file

src/OpenSage.Game/Data/InstallationLocator.cs
I only use windows, but dont do always a clean new installation of the games on my various systems, I simply copy them over. So it would be neat to simply set the installation path as on linux.
Also added a check if the found path exists, so the viewer does not crash if the installation folder was moved or deleted.
=> Fix for issue #174: installation locator

src/OpenSage.Viewer/UI/MainForm.cs, src/OpenSage.Viewer/Util/ImGuiUtility.cs
* Cache search results. They're now only computed when the search changes. This has a fairly major (positive) FPS impact.
* Fix null-terminator issues with input boxes (thanks @Qibbi!)
* Clear search box when installation changes.
* Small optimizations
=> Viewer file search improvements

src/OpenSage.Game/Content/MapLoader.cs, src/OpenSage.Game/Gui/TextCache.cs
Replace calls to `DangerousGetPinnableReferenceToPixelBuffer` with `MemoryMarshal.GetReference(image.GetPixelSpan()))` as pointed out by the deprecation warning message.
Replace call to `Unsafe.InitBlock` with `Span.Clear`.
=> Fix ImageSharp warnings

src/OpenSage.Game/Content/MapLoader.cs
It previously defaulted to the (pink) placeholder texture.
=> Fix missing macro and cloud textures in BFME maps

src/OpenSage.Game/Logic/Object/Draw/W3dModelDraw.cs
Final fix for #31.
Incidentally, `AllBuildingsAllSidesUnitTest_Save.map` is a great stress test, which OpenSAGE currently... fails :)
=> Allow null model for animation

src/OpenSage.Game/Assets/Shaders/Mesh.h, src/OpenSage.Game/Content/ModelLoader.cs, src/OpenSage.Game/Data/W3d/W3dShaderMaterialProperty.cs, src/OpenSage.Game/Graphics/Effects/ConstantBuffer`1.cs, src/OpenSage.Game/Graphics/Effects/MeshMaterial.cs, src/OpenSage.Game/Graphics/Shaders/Bool32.cs, src/OpenSage.Game/Graphics/Shaders/Bool4.cs, src/OpenSage.Game/Graphics/Shaders/FixedFunction.cs
- Adds a Bool4 type in C# that matches the 4 byte bools in GLSL.
- Change ConstantBuffer to use the unsafe sizeof operator which returns the "real" size of the underlying type (only relevant for `bool` type)
=> Fix GLSL/C# mismatches

src/OpenSage.Game/Audio/AudioSystem.cs, src/OpenSage.Game/Data/Ini/AudioEvent.cs, src/OpenSage.Game/Data/Rep/ReplayChunk.cs, src/OpenSage.Game/Data/Utilities/Extensions/BinaryReaderExtensions.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/GameObjectCollection.cs, src/OpenSage.Game/Logic/Orders/Order.cs, src/OpenSage.Game/Logic/Orders/OrderArgumentType.cs, src/OpenSage.Game/Logic/Orders/OrderArgumentValue.cs, src/OpenSage.Game/Logic/Orders/OrderProcessor.cs, src/OpenSage.Game/Logic/Orders/OrderType.cs, src/OpenSage.Game/Logic/Player.cs, src/OpenSage.Game/Logic/SelectionSystem.cs, src/OpenSage.Game/Mathematics/Rectangle.cs, src/OpenSage.Game/Network/NetworkMessageBuffer.cs, src/OpenSage.Game/Scene3D.cs, src/OpenSage.Mods.Generals/Gui/ReplayMenuCallbacks.cs, src/OpenSage.Viewer/UI/Views/MapView.cs
Based on #183 
* Implement selection barks (_Are there not better tools?_)
* Modify `SelectionSystem` so that unit selection events are passed through `NetworkMessageBuffer` and `OrderProcessor`. 
* Fix Generals replay menu crash
* Parse `ScreenRectangle` order arguments and `DrawBoxSelection` orders from replays
* Process local orders locally
=> Unit selection 1.5

src/OpenSage.Viewer/UI/MainForm.cs, src/OpenSage.Viewer/UI/Views/ManifestView.cs, src/OpenSage.Viewer/UI/Views/WndView.cs, src/OpenSage.Viewer/Util/ImGuiUtility.cs
Now we are able to see full filename in any cases. Just hover the mouse on the item and it's full name will be displayed.
Effect:
=> Added a tooltip to display full filename / item name

src/OpenSage.Game/Diagnostics/AssetViews/ModelView.cs, src/OpenSage.Game/Diagnostics/DeveloperModeView.cs, src/OpenSage.Game/Diagnostics/GameLoopView.cs, src/OpenSage.Game/Diagnostics/GameView.cs, src/OpenSage.Game/Diagnostics/MainView.cs, src/OpenSage.Game/Diagnostics/RenderedView.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/GameSystem.cs, src/OpenSage.Game/GameTimer.cs, src/OpenSage.Game/Graphics/Animation/AnimationInstance.cs, src/OpenSage.Game/Graphics/Cameras/ArcballCameraController.cs, src/OpenSage.Game/Graphics/Cameras/CameraAnimation.cs, src/OpenSage.Game/Graphics/Cameras/ICameraController.cs, src/OpenSage.Game/Graphics/Cameras/RtsCameraController.cs, src/OpenSage.Game/Graphics/ModelInstance.cs, src/OpenSage.Game/Gui/Apt/AptWindowManager.cs, src/OpenSage.Game/Gui/DebugUI/DebugOverlay.cs, src/OpenSage.Game/Gui/Wnd/WndWindowManager.cs, src/OpenSage.Game/Logic/Object/Draw/DrawModule.cs, src/OpenSage.Game/Logic/Object/Draw/W3dModelDraw.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Scene2D.cs, src/OpenSage.Game/Scene3D.cs, src/OpenSage.Game/Scripting/ScriptExecutionContext.cs, src/OpenSage.Game/Scripting/ScriptingSystem.cs, src/OpenSage.Game/Terrain/Bridge.cs, src/OpenSage.Game/Utilities/TimeSpanUtility.cs
(Partially) resolves  #102.
* Splits updates into 2 kinds:
* `LogicTick`
* Run at 5Hz
* Used for networking, order processing, unit movement etc.
* `LocalLogicTick`
* Runs on every frame
* Should be used for everything else, including input handling, UI updates, animation, interpolation etc. 
* Splits timers into 2 kinds:
* `MapTime` (name can be changed)
* Only runs when logic ticks are running; relative to the start of the current map (hence the name)
* Reset to 0 when the map changes 
* Should be used for timing things that should pause when the game is paused (interpolation, animation, particles, camera animation)
* `RenderTime`
* Runs continuously and never resets.
* Used for things that things that update even when the game is paused: Imgui, rendering, tracing/logging
* Map scripts …
=> Better game loop

src/OpenSage.Game/Content/ContentManager.cs, src/OpenSage.Game/Data/Ini/IniDataContext.cs, src/OpenSage.Game/Diagnostics/GameTrace.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/Graphics/Shaders/ShaderResourceManager.cs, src/OpenSage.Launcher/Program.cs
This adds support for optionally outputting trace data to a .json file, which can then loaded into Chrome's profiler at chrome://tracing. This PR just adds very basic support, which needs to be fleshed out with more tracing calls.
=> Add initial support for trace output

src/OpenSage.Game.Tests/Gui/Apt/ActionScript/InstructionParsingTest.cs, src/OpenSage.Game/Data/Apt/Characters/Button.cs, src/OpenSage.Game/Data/Apt/FrameItems/Action.cs, src/OpenSage.Game/Data/Apt/FrameItems/InitAction.cs, src/OpenSage.Game/Data/Apt/FrameItems/PlaceObject.cs, src/OpenSage.Game/Gui/Apt/ActionScript/InstructionCollection.cs, src/OpenSage.Game/Gui/Apt/ActionScript/InstructionStream.cs
By using `SortedList<int, InstructionBase>`, instruction's position is stored together with instruction itself, which allows fast retrieval of a instruction by its position, and we can avoid to manually calculate branch offsets, so things become a lot simpler xD
(Actually I think we can even remove `InstructionBase.Size` since it's not needed anymore)
=> Use SortedList to simplify InstructionCollection

src/OpenSage.Game/Logic/SelectionSystem.cs
fixes the drag selection of all objects, and limits it to local player objects instead
=> only allow drag-selection for own units

src/OpenSage.Game/Data/FileSystem.cs, src/OpenSage.Game/Data/SkudefReader.cs
C&C3 and above used `.skudef` files to define which `.big` files to load, and in which order. Our `FileSystem` implementation now uses these files when loading `.big` archives.
I've made it work for pre-C&C3 games by creating a dummy `.skudef` for those games which justs loads all `.big` files in an alphabetical order. If it turns out that order is important for any pre-C&C3 game, we can improve this by allowing each game to define its own default `.skudef`.
I also improved performance of file lookup by making all paths lowercase.
=> Implement .skudef reader

src/OpenSage.Game/Gui/Apt/AptRenderer.cs
It makes no sense to scale the geometry in when there is no parent AptWindow
=> Fix scaling being applied in geometry view

src/OpenSage.Game/Content/ContentManager.cs, src/OpenSage.Game/Content/SubsystemLoader.cs, src/OpenSage.Game/Diagnostics/MainView.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Launcher/Program.cs
This PR contains the following changes:
* Added a `FileSystem` for the `UserData` folder
* Added code for parsing the `MapCache.ini` file from that folder
* Enabled loading of user maps via command line option and dev mode menu
* Cached and sorted the valid maps for the dev mode menu
=> Enable loading of maps from UserData folder

src/OpenSage.Game/Scene3D.cs
`GameObjects` were added twice to the collection because `FromMapObject` already calls `parent.Add(mapObject.TypeName)`.
=> Fix duplicate GameObject insertion

src/OpenSage.Game/Graphics/Rendering/RenderItemCollection.cs, src/OpenSage.Game/Terrain/HeightMap.cs, src/OpenSage.Game/Terrain/RoadCollection.cs
This PR applies the same ordering to road textures as original SAGE. It should also stop the flickering of roads depending on the camera position.
=> Correct z-ordering for roads

src/OpenSage.Game/Data/FileSystem.cs
The **Load replays** button was crashing since it tried mounting the **Replays** folder which doesn't exist
=> Don't crash for non existent filesystems

src/OpenSage.Game/Graphics/Cameras/RtsCameraController.cs
`RtsCameraController` casts a ray against the terrain each frame to automatically adjust the distance. The code currently assumes there's always an intersection, which would make sense in an RTS game. However this isn't always the case, because map scripts can adjust the camera pitch. This causes a crash in the intro cutscenes in maps like CHI02 and CHI04.
This PR alters the camera controller to reuse the previous successful distance measurement when a raytrace fails. It's probably not accurate to the original engine, but at least it no longer crashes.
=> Reuse previous camera-terrain distance if raycast fails

src/OpenSage.Game/Terrain/Roads/CrossingRoadSegment.cs, src/OpenSage.Game/Terrain/Roads/CurvedRoadSegment.cs, src/OpenSage.Game/Terrain/Roads/ISimpleRoadSegment.cs, src/OpenSage.Game/Terrain/Roads/IncomingRoadData.cs, src/OpenSage.Game/Terrain/Roads/RoadConstants.cs, src/OpenSage.Game/Terrain/Roads/RoadNetwork.cs, src/OpenSage.Game/Terrain/Roads/RoadSegmentMesher.cs, src/OpenSage.Game/Terrain/Roads/RoadTopology.cs, src/OpenSage.Game/Terrain/Roads/StraightRoadSegment.cs, src/OpenSage.Game/Terrain/Roads/TextureAtlas.cs
Adds support for tight and broad curves.
The texture mapping isn't perfect, but then again, neither is the orignal.
The decision which curve type is chosen is somewhat arbitrary (see #341), this algorithm isn't implemented yet. We only use tight and broad curves if both edges agree on the type.
=> Curved roads

src/OpenSage.Game/Graphics/ModelMesh.W3d.cs, src/OpenSage.Game/Graphics/Shaders/ShaderMaterialShaderResources.cs
Unfortunaly the shade indices don't work with BFME models, so we fallback to plain traingles indices
=> Fix wrong indices for BFME models

src/OpenSage.Game/Data/FileSystem.cs, src/OpenSage.Mods.Generals/Gui/MapUtils.cs
This fixes a crash on linux, which happened because `Path.GetDirectoryName(mapPath)` was invalid on unix systems. The path must be normalized first for this to work
=> Fix wrong path seperator issue

src/OpenSage.Game/Gui/Wnd/Images/Image.cs
We were downsampling textures, only to upsample them again when rendering, which looked terrible.
=> Improve wnd image quality

src/OpenSage.Game/Content/AssetStore.cs, src/OpenSage.Game/Data/Ini/IniParser.BlockParsers.cs, src/OpenSage.Game/Data/Ini/IniParser.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/ObjectDefinition.cs, src/OpenSage.Game/Logic/Object/Production/ProductionJob.cs, src/OpenSage.Game/Logic/Object/Update/ProductionUpdate.cs, src/OpenSage.Game/Logic/Object/UpgradeDefinition.cs, src/OpenSage.Game/Logic/Object/UpgradeTemplate.cs, src/OpenSage.Game/Logic/Orders/OrderProcessor.cs, src/OpenSage.Game/Logic/Orders/OrderType.cs, src/OpenSage.Game/Scene3D.cs, src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
* Adds upgrades to the production queue
* Use **BuildTime** instead of **BuildCost**. This is still different from the original games production speed. We probably need to take of GameSpeed aswell.
* Each gameobject has a list of granted upgrades
=> Work on object upgrades

src/OpenSage.Game/Content/MapCache.cs, src/OpenSage.Game/Data/FileSystem.cs, src/OpenSage.Game/Data/Map/MapFile.cs, src/OpenSage.Game/Data/Map/UserMapCache.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/Scene3D.cs, src/OpenSage.Game/Scripting/Waypoints.cs
Generate the MapCache.ini for user maps on startup. This needs to be done because the user maps could have been modified.
The CRC is still missing (as we don't know the exact algorithm yet) and so are the properties added after ZH.
It's still useful already because you don't have to start the original games any more to generate the file when a new map is added.
=> UserData MapCache.ini

src/OpenSage.Game/Data/Map/UserMapCache.cs
`GenerateMapCacheIniFile` assumes the `Maps/` folder exists in the user data directory, added a call to create the directory if it does not exist preventing crash on startup when game not ran before.
=> Fix maps directory not being created for map cache

src/OpenSage.FileFormats.W3d/W3dVertexInfluence.cs
Sometimes both bone weights are 0, set bone weight 1 to 100 in that case.
before:
after:
=> Fixed bone weight issue

src/OpenSage.Game/Logic/Orders/OrderProcessor.cs, src/OpenSage.Game/Logic/SelectionSystem.cs
At the moment units and buildings can be selected at the same time. 
After this fix units are prioritized in order to still be able to set waypoints for them etc.
If multiple structures are in the selected region, only the first one in the list will be selected.
=> Fixed multi selection

src/OpenSage.Game/Gui/Wnd/Images/Image.cs, src/OpenSage.Game/Gui/Wnd/Images/MappedImageSource.cs, src/OpenSage.Game/Gui/Wnd/Images/MappedImageUtility.cs
A user on our discord server recognized that Wnd images are a bit blurry / not the full resolution.
There are multiple recognized:
- The texture size depends on the size of the Wnd control, but we always want the full resolution
- The images do get rendered into a framebuffer and then rendered again. I'm not sure if this lowers quality, but it definetly is less efficient than a plain `commandList.CopyTexture` 
I solved this by using the original texture data when possible. However not sure how to solve this for stretchable images. 
Also i think we need to reconsider the **ImageSource** interface. Opinions welcome
=> Avoid reducing mapped images quality

src/OpenSage.Game/Logic/OrderGenerators/SpecialPowerOrderGenerator.cs, src/OpenSage.Game/Terrain/RadiusCursorDecals.cs, src/OpenSage.Game/Terrain/Terrain.cs, src/OpenSage.Game/Utilities/TextureMipMapData.cs
My initial implementation only supported the radius cursor decals loaded from InGameUI.ini. With this change, we can support all the others such as the ones in `DeliveryDecal`.
=> Handle all radius decals, not only the ones in InGameUI.ini

src/OpenSage.Game/Logic/Object/Draw/W3dModelDraw.cs
This fixes that some condition states are not drawing incorrectly drawn. @Tarcontar and me found that issue while workying on the chinook. What happened is the following. 
There were the following condition states:
*(CARRYING, RUBBLE)* <-- This was picked
*(DOCKING, CARRYING. RUBBLE)*
*(CARRYING)* <-- This should be picked
*(DOCKING, CARRYING)*
When now selecting **CARRYING** it would just pick the first condition state it found, since all 4 condition states have 1 intersecting bit. However it should always pick the condition state with the least bits.
I think this fixed also multiple other animations, atleast build animations look more correct now sometimes :)
=> Fix wrong condition state selection

src/OpenSage.Game/Data/Ini/IniParser.cs
Fixes a memory leak caused by a lambda in `IniParser.ParseAudioEventReference` capturing the entire parser object by reference even though it only requires the `_assetStore` field. Fixed by extracting the field into a local variable first.
Reduces memory consumption by 20-30 megabytes in the ZH main menu.
=> Fix INI parser leak from ParseAudioEventReference

src/OpenSage.Game/Graphics/ModelInstance.cs
The visibility animations for the SupplyCenter (hiding & showing the boxes) didn't work. 
I think the current code did not check the parent visibility correctly
=> Fix bone visibility

src/OpenSage.Game/Content/Loaders/OnDemandGuiTextureLoader.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/Terrain/Roads/CrossingRoadSegment.cs, src/OpenSage.Game/Terrain/Roads/CurvedRoadSegment.cs, src/OpenSage.Game/Terrain/Roads/RoadNetwork.cs, src/OpenSage.Game/Terrain/Roads/RoadSegmentMesher.cs, src/OpenSage.Launcher/Program.cs
Fixes #468
I also added a workaround for loading user map textures and implemented a "restart" function (when a map name is passed via the command line, pressing `Break` reloads that map).
=> Road improvements

src/OpenSage.Game/Input/Cursors/Cursor.cs, src/OpenSage.Game/Utilities/PlatformUtility.cs, src/OpenSage.Game/Utilities/Sdl2Interop.cs
- Use correct platform DPI for Gnome3
- Use ImageSharp to scale the cursor pixeldata, since **BlitSurface** crashes the executable
=> Linux fixes

src/OpenSage.Core/NLog.config, src/OpenSage.Game/Audio/AudioSystem.cs, src/OpenSage.Game/Content/ContentManager.cs, src/OpenSage.Game/Content/Loaders/OnDemandAudioFileLoader.cs, src/OpenSage.Game/Content/SubsystemLoader.cs, src/OpenSage.Game/Diagnostics/MainView.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/Logic/PlayerSettings.cs, src/OpenSage.Game/Scene3D.cs, src/OpenSage.Game/Scripting/Actions/ScriptActions.Multimedia.cs, src/OpenSage.Game/Scripting/Conditions/ScriptConditions.Multimedia.cs, src/OpenSage.Game/Scripting/Conditions/ScriptConditions.Skirmish.cs, src/OpenSage.Game/Scripting/Script.cs, src/OpenSage.Game/Scripting/ScriptAction.cs, src/OpenSage.Game/Scripting/ScriptArgument.cs, src/OpenSage.Game/Scripting/ScriptArgumentPlaceholders.cs, src/OpenSage.Game/Scripting/ScriptCondition.cs, src/OpenSage.Game/Scripting/ScriptContent.cs, src/OpenSage.Game/Scripting/ScriptGroup.cs, src/OpenSage.Game/Scripting/ScriptList.cs, src/OpenSage.Game/Scripting/ScriptOrCondition.cs, src/OpenSage.Game/Scripting/ScriptingSystem.cs, src/OpenSage.Launcher/Program.cs
Music playback is controlled via the SkirmishScripts (at least in Generals and Zero Hour). I added code for loading and "instatiating" these scripts (copying them for each player and making sure script-, variable- and team-names are unique) and implemented the script actions and conditions necessary for music playback.
There's probably still a lot missing (e.g. I didn't import teams for now, I don't check if there are already scripts in the map file that need to be preserved, there's no fade-in or fade-out, and so on). But I think the PR is big enough already and basic playback works for Generals and Zero Hour. :)
=> Music playback via Skirmish Scripts

src/OpenSage.Game/OpenSage.Game.csproj
Updates the SharpAudio version dependency that will allow systems that use OpenAL as their Audio SubSystem, such as Linux, to start. Previously it wouldn't start at all.
=> Updated SharpAudio Version

src/OpenSage.Game/Diagnostics/MainView.cs
If the renderdoc failed to load, the program will crash if pressing on any of the renderdoc menu items. By disabling the renderdoc menu item it will prevent the program to crash but still show that the option was enabled.
=> Disable RenderDoc menu item if renderdoc failed to load.

src/OpenSage.Game/Assets/Shaders/Sprite.frag
The OpenGL rendering of the UI didn't always rendering probably such as the main menu. It seems to to have been the cause by the sprite fragment shader. It would call textureSize(AlphaMask_1, 0) for getting the size for computing the UV for the getting the alphaMaskColor. The AlphaMask_1 sampler2D is just a dummy created by the glslangValidator and is never bounded texture object.
=> Fix issue with weird UI Rendering on OpenGL

src/OpenSage.Game/Content/SubsystemLoader.cs, src/OpenSage.Game/Logic/Object/AnimationState.cs, src/OpenSage.Game/Logic/Object/Draw/W3dModelDraw.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Update/ExperienceUpdate.cs, src/OpenSage.Mathematics/BitArray`1.cs
- only update modelconditionstate and animationstate if any of the ModelConditionFlags has changed
- IdleAnimations are not "repeated" anymore, that means e.g. a door open animation only plays once, but we still shuffle through the various idle animations of a unit
=> Idle animation state

src/OpenSage.Game/Gui/Apt/RenderItem.cs
Fixes text rendering when the string passed was null
=> fix apt text rendering nullptr

src/OpenSage.Game/Assets/Shaders/Shadows.h, src/OpenSage.Game/Assets/Shaders/Terrain.frag
It seems that the samplerless has been the cause of the screen being black https://github.com/OpenSAGE/OpenSAGE/issues/389 when using OpenGL on some drivers that do not support the GL_EXT_samplerless_texture_functions extension.
=> Removed samplerless to prevent black screen on OpenGL

src/OpenSage.Game/Content/AssetHash.cs, src/OpenSage.Game/Content/AssetStore.cs, src/OpenSage.Game/Content/Translation/Providers/CsfTranslationProvider.cs, src/OpenSage.Game/Data/Dds/DdsFile.cs, src/OpenSage.Game/Data/SkudefReader.cs, src/OpenSage.Game/Data/StreamFS/AssetType.cs, src/OpenSage.Game/Data/StreamFS/GameStream.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/Logic/Object/GameObjectCollection.cs
- Added a simple version system for skudef, allowing OpenSage to load the lastest skudef (d37b854)
- Removed empty csf category warning for RA3 (1845c0f)
- Fixed case sensitive asset hash (it was incorrectly using case insensitive hash) (81fb8aa)
- Support `DdsImageFormat.Rgba16Float` (b7fb56a)
- Allows `OpenSage.Data.StreamFS.GameStream` to conditionally skip parsing binary assets based on current `SageGame` type (Mainly audio files, they don't work yet on RA3 right now) (1888aa9)
- Allow `AssetType` override based on `SageGame` (f1c6d79), because the same asset might have different names (so different asset id) in different games 
- Removed duplicate warnings in `GameObjectCollections` (e8335b2), now `[Warn] Skipping unknown GameObject {Type}` will be logged only once per each different …
=> Miscellaneous changes and small fixes

src/OpenSage.Game/Data/Sav/SaveFile.cs, src/OpenSage.Game/Diagnostics/MainView.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/Logic/Player.cs, src/OpenSage.Game/Logic/PlayerSettings.cs, src/OpenSage.Launcher/Program.cs, src/OpenSage.Mods.Generals/Gui/GameOptionsUtil.cs
This utilized the teams configured in a skirmish lobby and populates each player's allies/enemies.
=> Add teams and configure allies/enemies

src/OpenSage.Game/Logic/Object/Update/AIUpdate/TurretAIUpdate.cs
Vehicles like the GLA Radar Van have no Weapon Set defined, and thus CurrentWeapon will never be anything but null for them.
=> Fix #532 add null check on CurrentWeapon in TurretAIUpdate

src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
With this, all the buttons in Zero Hour show up as they should.
I think a maximum of 99 buttons should suffice. :) I chose that number simply because of the naming scheme of ButtonCommandXX with it starting at 01.
Refs #462
=> Generals & ZH command bar button limit = ButtonCommand children in ControlBar.wnd (max 99)

src/OpenSage.Game/Data/FileSystem.cs
Do not normalize path in FileSystem constructor.
NormalizeFilePath() lowercase paths, this break on linux ("/Command and Conquer Generals" become "/command and conquer generals") and crash calling OpenSage.Utilities.LanguageUtility.DetectFromFileSystem()
=> Revert Normalize FileSystem's root directory

src/OpenSage.Game.Tests/Mods/Generals/StartingPositionAssignmentTests.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/Gui/Wnd/Controls/ComboBox.cs, src/OpenSage.Game/Gui/Wnd/Controls/ListBox.cs, src/OpenSage.Game/Network/NetworkConnection.cs, src/OpenSage.Game/Network/Packets/SkirmishClientUpdatePacket.cs, src/OpenSage.Game/Network/SkirmishGameSettings.cs, src/OpenSage.Game/Network/SkirmishManager.cs, src/OpenSage.Game/Network/SkirmishSlot.cs, src/OpenSage.Mods.Generals/Gui/GameOptionsUtil.cs, src/OpenSage.Mods.Generals/Gui/LanGameOptionsMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/LanMapSelectMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/MainMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/NetworkUtils.cs, src/OpenSage.Mods.Generals/Gui/SkirmishGameOptionsMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/SkirmishMapSelectMenuCallbacks.cs
Skirmish games are now handled in the same way as LAN games. Previously, they worked differently with the state (player positions, colors, teams, ...) being only implicitly stored in the UI controls. Now they use the same model (`SkirmishGameSettings`, formerly known as `SkirmishGame`) as LAN games, which makes the code cleaner and simpler.
Based on that, the starting position setup now also works for network games.
=> Skirmish refactoring

src/OpenSage.Mods.Generals/Gui/GameOptionsUtil.cs, src/OpenSage.Mods.Generals/Gui/LanMapSelectMenuCallbacks.cs, src/OpenSage.Mods.Generals/Gui/SkirmishMapSelectMenuCallbacks.cs
Without actively selecting a map the mapname was not set
=> Fix crash in lobby

src/OpenSage.Game/Utilities/LanguageUtility.cs
This fixes an issue when a game on windows is installed without the registry containing the language. Before it would always try to use **DefaultLanguage**
=> Fix language detection for non-registry installations

src/OpenSage.Game/Logic/Object/Behaviors/SlowDeathBehavior.cs, src/OpenSage.Game/Logic/Object/Body/BodyModule.cs, src/OpenSage.Game/Logic/Object/ClientUpdate/ClientUpdate.cs, src/OpenSage.Game/Logic/Object/Collide/CollideModule.cs, src/OpenSage.Game/Logic/Object/Contain/ContainModule.cs, src/OpenSage.Game/Logic/Object/Create/CreateModule.cs, src/OpenSage.Game/Logic/Object/Damage/DamageModule.cs, src/OpenSage.Game/Logic/Object/Die/DieModule.cs, src/OpenSage.Game/Logic/Object/Draw/DrawModule.cs, src/OpenSage.Game/Logic/Object/Module.cs, src/OpenSage.Game/Logic/Object/ObjectDefinition.cs, src/OpenSage.Game/Logic/Object/SpecialPower/SpecialPower.cs, src/OpenSage.Game/Logic/Object/Update/UpdateModule.cs, src/OpenSage.Game/Logic/Object/Upgrade/UpgradeModule.cs
This is a follow-up to #558. I've discovered that "default" module inheritance isn't just based on a single "module kind" for each module. For example, a `SlowDeathBehavior` will override both `Update` and `Die` modules from the `DefaultThingTemplate`. So we need to use a flags enum and bitwise-and to compare the module kinds.
=> Use bitwise-and to compare module kind(s) for module inheritance

src/OpenSage.Mods.Generals/Gui/GameOptionsUtil.cs
The color slot was defaulting to gold and the team slot was defaulting to 1. This also disables slot editing when a "player" (human or AI) is not present.
=> Fix skirmish menu slots

src/OpenSage.Game/Data/SkudefReader.cs, src/OpenSage.Game/Utilities/LanguageUtility.cs
Fixes the problem of not finding the skudef file for RA3 and Uprising, by ignoring the letter case, Additionally normalizing the file paths constructed from the skudef file.
Also added to extract the default language for RA3 and Uprising.
=> Fix skudef extension file not found for RA3 and Uprising

src/OpenSage.Game/Data/Apt/FrameItems/PlaceObject.cs, src/OpenSage.Game/Diagnostics/AptGeometryView.cs, src/OpenSage.Game/Gui/Apt/ActionScript/Library/Builtin.cs, src/OpenSage.Game/Gui/Apt/AptRenderingContext.cs, src/OpenSage.Game/Gui/Apt/DisplayItem.cs, src/OpenSage.Game/Gui/Apt/SpriteItem.cs, src/OpenSage.Mathematics/ColorRgbaF.cs
https://github.com/OpenSAGE/OpenSAGE/discussions/648
Known issues:
Adobe / [Macromedia's specification](https://www.ics.agh.edu.pl/dydaktyka/mm/lato0405_inf_d/wyklady/w4/SWF7_specification.pdf) says that during every transformation, colors needs to be clamped between 0 and 255.
But we are currently "abusing" the associativity of `ItemTransform` to calculate a pre-computed color transform.
This approach do work, if we ignore about clamping, the pre-computed color transform is equivalent to applying multiple color transforms separately because of the associativity rule.
But if we consider the clamping, then... we might need to rewrite the entire `ItemTransform`...
=> Support additive ColorTransform

src/OpenSage.Game/Logic/Object/BehaviorModule.cs, src/OpenSage.Game/Logic/Object/Behaviors/CastleBehavior.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/AIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/DozerAIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/IBuilderAIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/WorkerAIUpdate.cs, src/OpenSage.Game/Logic/OrderGenerators/ConstructBuildingOrderGenerator.cs, src/OpenSage.Game/Logic/Orders/OrderProcessor.cs
This isn't perfect, but should be a start at the dozer logic.
This PR changes building construction so that:
- construction doesn't begin until the dozer is at the building 
- _**future task** - define a new destination for the dozer that is at the edge of the building instead of directly inside it_
- construction pauses when the dozer is ordered away
- _**future task** - add commands to allow dozer to be ordered back to resume construction_
- construction no longer relies on the logic frame on which construction was started, and instead tracks the logic frame span over which construction has occurred
The logic between the AI handler for Dozers and Workers is duplicated, so it might be nice to extract that out into a separate module in the future. It also results in a cast in …
=> Delay building construction until dozer arrives on site

src/OpenSage.Game/Data/Map/SidesListUtility.cs
Makes two players on team None _actually_ enemies, and makes two players on team 1 _actually_ allies.
Related to #678. Neutral is no longer enemy of everybody. They're still allies with everybody so potentially some work to do there.
=> Fix incorrect teams

src/OpenSage.Game/Diagnostics/AssetViews/TextureAssetView.cs, src/OpenSage.Game/Diagnostics/AssetViews/TextureView.cs, src/OpenSage.Game/Diagnostics/MainView.cs, src/OpenSage.Game/Diagnostics/PreviewView.cs, src/OpenSage.Game/Diagnostics/TextCacheView.cs, src/OpenSage.Game/Graphics/Rendering/RenderPipeline.cs, src/OpenSage.Game/Gui/Apt/AptRenderingContext.cs, src/OpenSage.Game/Gui/DrawingContext2D.cs, src/OpenSage.Game/Gui/TextCache.cs, src/OpenSage.Game/Scripting/CameraFadeOverlay.cs, src/OpenSage.Game/Utilities/Extensions/EnumerableExtensions.cs, src/OpenSage.Game/Utilities/ResourcePool.cs, src/OpenSage.Mathematics/Size.cs
Depends on #701.
* Implement cache expiration for the text cache. Textures which not have been used for 5 seconds are purged from the cache at the end of each render frame.
* Add a new dev mode view for exploring text cache entries.
* To support the dev mode view the asset preview system has been extended to support raw Veldrid textures in addition to `TextureAsset`s.
* Vertical text centering has been fixed 🎉 
* Small optimizations to text rendering. For example, fully transparent text is no longer rendered.
=> Text cache expiration & debug view

src/OpenSage.Game/Logic/Object/Draw/W3dSupplyDraw.cs, src/OpenSage.Game/Logic/Object/Update/SupplyWarehouseDockUpdate.cs
Fixes #682 
Tested in Generals and seems to work for supply docks as well as supply piles.
=> Hide supply box bones as supplies are depleted

src/OpenSage.Game/Logic/Object/UnitSpecificSounds.cs, src/OpenSage.Game/Logic/Object/Update/ProductionUpdate.cs, src/OpenSage.Game/Logic/OrderGenerators/ConstructBuildingOrderGenerator.cs
This also fixes a small bug where dozers would play the `VoiceCreate` sound when building something, when they instead should be playing the `VoiceBuildResponse` sound.
=> Play VoiceCreate sound when unit is produced

src/OpenSage.Game/Logic/Object/Update/AIUpdate/DozerAIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/IBuilderAIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/WorkerAIUpdate.cs, src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
Fixes #694 
This is the second place I've written a kindof check followed by an AIUpdate cast. Not sure if this is something that will become more common and we should consider ways to get more discrete GameObject types?
=> Disable DOZER_CONSTRUCT commands while dozer is building

src/OpenSage.Game/Gui/Wnd/Controls/Control.cs, src/OpenSage.Game/Logic/Object/Create/VeterancyGainCreate.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Mods.Generals/Gui/CommandButtonUtils.cs, src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
A unit which is promoted now appears as such in the cameo window
Additionally, the chevrons appear in production where applicable (this is with the technical veterancy science)
Without the veterancy science, they aren't present
I also went ahead and added a veterancy dropdown to the debug tool
=> Show veterancy overlays in control bar

src/OpenSage.Game/Logic/Object/ObjectDefinition.cs, src/OpenSage.Game/Logic/Object/Update/ProductionUpdate.cs, src/OpenSage.Game/Logic/Orders/OrderProcessor.cs
I actually wasn't able to find any cases in Generals where `SoundMoveStartDamaged` differed from `SoundMoveStart`.
=> Play SoundMoveStart and SoundMoveStartDamaged when moving

src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
This just hides the production queue button if there isn't a unit actively being produced in that button slot, so that it can't be clicked or trigger a null callback.
=> Fix clicking empty queue button causes crash

src/OpenSage.Game/Logic/Object/Draw/W3dTruckDraw.cs, src/OpenSage.Game/Logic/Object/GameObject.cs
Note that the objects don't currently have their ModelConditionFlags updated with `NIGHT`. This does, however, update the inspector to allow for setting ModelConditionFlags (and supports enabling/disabling multiple flags).
`NIGHT`:
`NONE`:
=> Disable headlights when not night

src/OpenSage.Game/Audio/AudioSystem.cs, src/OpenSage.Game/Content/Loaders/OnDemandAudioFileLoader.cs, src/OpenSage.Game/Content/SubsystemLoader.cs, src/OpenSage.Game/Scripting/Actions/ScriptActions.Multimedia.cs
The one thing I'm not sure about here is adding `Data\INI\Speech.ini` to `SubsystemLoader`. Was it not added in the first place because BFME or other games don't have it?
Otherwise, this is pretty cool because it plays the voice lines on the shellmap.
=> Play speech files from scripts

src/OpenSage.Game/Logic/Object/Update/ProductionUpdate.cs
Not sure about the other sage games, but this is the way it works in generals/zero hour.
Before:
After:
=> Spawn unit after door opens, not before

src/OpenSage.Game/Game.cs
A bit of a hack, but it does get the sav2json tool working (though it still crashes upon completion of writing the json file, but at least it's able to write the json file).
This cropped up with one of the recent library upgrades.
=> Fix NPE when running Sav2Json tool

src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
=> Apply Hover and Pushed overlay images to production queue

src/OpenSage.Game/Gui/Wnd/Controls/Button.cs, src/OpenSage.Game/Gui/Wnd/Controls/Control.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
In this screenshot, the flashbang upgrade has already been purchased, and the capture upgrade is queued. As such, both are disabled, but are _not_ grayscale.
=> Use BuildUpClockColor overlay for purchased upgrades

src/OpenSage.Game/Gui/Wnd/Controls/Button.cs, src/OpenSage.Game/Gui/Wnd/Controls/Control.cs, src/OpenSage.Game/Logic/Object/Behaviors/OverchargeBehavior.cs, src/OpenSage.Game/Logic/Object/Update/PowerPlantUpdate.cs, src/OpenSage.Game/Logic/Object/Update/UpdateModule.cs, src/OpenSage.Game/Logic/Orders/OrderProcessor.cs, src/OpenSage.Mods.Generals/Gui/CommandButtonUtils.cs, src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
Not sure if this is how UpdateModules were intended to be handled. From what I can tell in the save file, what I've renamed here to `NextUpdateFrame` is the next frame during which the UpdateModule should run. I checked my save file and this seems to apply to other modules like `DozerAIUpdate` as well (which presumably just updates every frame?). UpdateModules which aren't currently active (e.g. AutoHealBehavior in my file) seem to just have their frame set to uint maxvalue.
=> Implement OverchargeBehavior

src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Scene3D.cs
All behavior was tested against Zero Hour.
Health bars now change color as a unit is damaged. They go from `#00FF00` at full health to `#FFFF00` at 50% health and `#FF0000` at no health.
Health bars of under-construction structures are also changed, and now go from `#0000FF` at 0% health to `#00FFFF` at full health. The bar also shows health instead of construction progress. This means that if a structure is damaged while under construction, construction will complete before the bar reaches 100%. This is exactly how it behaves in Generals/Zero Hour. It also means a structure doesn't immediately have full health despite not being constructed at all - which of course makes sense, as in generals/zh scaffolds can be one-shot by basically anything that can damage them, and structures which …
=> Add color-changing health + construction bars

src/OpenSage.Game/Logic/Object/Body/BodyModule.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/ObjectDefinition.cs
This also adds the ability to damage and kill units in a specific way via the inspector, and removes the duplicate ActiveBody that was being displayed which caused for weird behavior.
=> Play die sounds on death

src/OpenSage.Game/Logic/Object/Update/ProductionUpdate.cs
Enables some extra animations on production structures. The blinking lights caused by ActivelyConstructing don't seem to be working on the airfield, but I've used the inspector to verify the ModelConditionFlags are as expected so it may just have to do with how we choose which states to animate (I know there's a lot more work to be done there).
=> Set ActivelyConstructing and ConstructionComplete ModelConditionFlags

src/OpenSage.Game/Logic/Object/Behaviors/CastleBehavior.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/AIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/DozerAIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/DozerAndWorkerState.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/IBuilderAIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/IBuilderAIUpdateData.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/WorkerAIUpdate.cs, src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
Also fixes flags which were being set correctly, and scaffolds behavior for repairing buildings.
This has slight consequences in that now no model is shown when a scaffold is placed and construction has not yet begun, but that's actually more correct - previously we were showing the scaffolding model which was incorrect. We should just be showing the fence model, which we weren't before and still aren't now (see #795)
=> Move construction management to DozerAndWorkerState

src/OpenSage.Game.Tests/Logic/Draw/W3dModelDrawTests.cs, src/OpenSage.Game/Logic/Object/Draw/W3dModelDraw.cs, src/OpenSage.Game/Logic/Object/GameObject.cs
This at least fixes the ModelConditionState selection issue mentioned in #795. However, it does not correct the animations or transitions. The transitions never play, and it seems either all drawables will rise from the ground or none of them will, rather than only the drawable with `ADJUST_HEIGHT_BY_CONSTRUCTION_PERCENT` set.
=> Select proper ModelConditionState when building structures

src/OpenSage.Game/Client/Drawable.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Weapon/Weapon.cs, src/OpenSage.Game/Logic/Object/Weapon/WeaponSet.cs, src/OpenSage.Game/Scene3D.cs, src/OpenSage.Mathematics/SizeF.cs
Pips show for weapons which have them enabled, and only when the unit is selected (notice the raptor is not selected, and so no pips are shown).
This new pip placement is objectively worse than a previous version of this PR, though I'll argue it surfaces the real issue which is that our health bars aren't positioned correctly. There's also the manner of the `PipScreenOffset` parameters, which I don't quite understand how to implement.
```ini
AmmoPipScreenOffset = X:-1.0 Y:0.0        ; note that this is a multiplier to boundingspheresize, NOT an absolute offset
ContainerPipScreenOffset = X:1.0 Y:0.0    ; note that this is a multiplier to boundingspheresize, NOT an absolute offset
```
=> Add ammo pips

src/OpenSage.Game/Logic/Object/Contain/GarrisonContain.cs, src/OpenSage.Game/Logic/Object/Contain/OpenContain.cs
Buildings without `GarrisonableUntilDestroyed` (i.e most garrisonable civilian buildings, but no garrisonable faction buildings) should have their contents evac'd when they reach the `ReallyDamaged` state, and should not be able to accept units in that state until repaired.
=> Force evac and prevent access to a building when it is ReallyDamaged

src/OpenSage.Game/Logic/Object/Contain/GarrisonContain.cs, src/OpenSage.Game/Logic/Object/Contain/TransportContain.cs
Missed this in a previous PR. Devious. The flags are set on both the module and the drawable. I'm not sure why.
=> Set Garrisoned/Loaded flags on drawable

src/OpenSage.Game/Client/Drawable.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Update/HordeUpdate.cs
I honestly wasn't sure of any other way to check for whether the player has the nationalism upgrade than to hardcode it. I don't see this defined as a parameter in GameData.ini or anywhere else. Should we create a game parameter for it? Do other games even use this UpdateBehavior, or is it specific to Generals/Zero Hour?
=> Add logic for HordeUpdate

src/OpenSage.Game/Logic/Object/Behaviors/AutoHealBehavior.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Update/BaseRegenerateUpdate.cs, src/OpenSage.Game/Logic/Object/Update/ISelfHealable.cs
Structures currently heal amusingly quickly due to #825. Otherwise, this works very similarly to `AutoHealBehavior`, just with significantly less complexity.
=> Implement BaseRegenerationUpdate

src/OpenSage.Game/Gui/CommandButtonCallback.cs, src/OpenSage.Game/Logic/OrderGeneratorSystem.cs, src/OpenSage.Game/Logic/OrderGenerators/SpecialPowerOrderGenerator.cs, src/OpenSage.Game/Logic/Orders/OrderProcessor.cs, src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
This expands upon the special power order generator to consider the owner of the target and use appropriately-defined cursors.
In the long-term, I'm not sure what the best course of action is here. It needs some way of identifying whether the target is valid (like the target of a cahs hack must be a supply center) but I haven't been able to find that defined anywhere in the inis.
=> Improve special power order generator

src/OpenSage.Game/Logic/Object/BehaviorModule.cs, src/OpenSage.Game/Logic/Object/Behaviors/InstantDeathBehavior.cs, src/OpenSage.Game/Logic/Object/Behaviors/SlowDeathBehavior.cs, src/OpenSage.Game/Logic/Object/Die/CreateCrateDie.cs, src/OpenSage.Game/Logic/Object/Die/CreateObjectDie.cs, src/OpenSage.Game/Logic/Object/Die/CrushDie.cs, src/OpenSage.Game/Logic/Object/Die/DamDie.cs, src/OpenSage.Game/Logic/Object/Die/DestroyDie.cs, src/OpenSage.Game/Logic/Object/Die/DieModule.cs, src/OpenSage.Game/Logic/Object/Die/EjectPilotDie.cs, src/OpenSage.Game/Logic/Object/Die/FXListDie.cs, src/OpenSage.Game/Logic/Object/Die/KeepObjectDie.cs, src/OpenSage.Game/Logic/Object/Die/RebuildHoleExposeDie.cs, src/OpenSage.Game/Logic/Object/GameObject.cs
This utilizes the `RequiredStatus` and `ExemptStatus` fields in the die behaviors which have at least partial implementations. It does not implement those fields in other behaviors (die or otherwise) which do not have implementations.
- `IsCorrectStatus` is defined in two separate places in this PR. I opted not to extract it out further as I don't know how the other non-die behaviors will use it (if at all). There are currently two other non-die behaviors that have these object status properties to my knowledge (`FireWeaponWhenDeadBehavior` and `FireWeaponCollide`).
- This adds an `ObjectStatus` field to `GameObject`, but does not persist it in any way. I _assume_ one of the unknown fields is this (how else would you persist whether a vehicle has been hijacked?), but I'm not sure. The …
=> Respect RequireStatus and ExemptStatus in die behaviors

src/OpenSage.Game/Logic/Object/Behaviors/SpawnBehavior.cs, src/OpenSage.Game/Logic/Object/Contain/OpenContain.cs, src/OpenSage.Game/Logic/Object/Contain/TransportContain.cs
Previously, units were spawning at map 0,0 (in the case of the tunnel network) or somewhere along the map edge (in the case of the stinger site).
It appears the issue with the tunnel network was that the productionexitbehavior was specifically commented out in inis with a comment that it falls back to opencontain, so I've implemented support for that here (including following the exit bones and rally points).
For the stinger site, it seems like `_productionExit.GetUnitCreatePoint()` was already in world space, and we transformed it _again_ resulting in some weird coordinates.
@Tarcontar looks like you wrote a lot of this code initially (if a while ago) so I wouldn't mind your eyes on it.
=> Fix GLATunnelNetwork GLAStingerSite SpawnBehavior

src/OpenSage.Game/Logic/Object/Contain/TunnelContain.cs
The DeathType is in fact Crushed. The damage dealt appears to be `999999` with DamageType Explosion in a Generals save, but I like our Kill function.
Requires #830 for CI build to pass
=> Kill all units in tunnels when last tunnel dies

src/OpenSage.Game/Logic/Object/Behaviors/SlowDeathBehavior.cs, src/OpenSage.Game/Logic/Object/Die/DieModule.cs, src/OpenSage.Game/Logic/Object/Die/EjectPilotDie.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/ObjectCreationList.cs, src/OpenSage.Game/Logic/Object/UnitSpecificSounds.cs
Determination between whether the unit is in the air or on the ground is still to be done.
Changes were made to SlowDeathBehavior because when a vehicle had a SlowDeathBehavior it meant we didn't run any other behaviors on die, which in this case we definitely do need to
Requires #830 for CI build to pass
=> Implement EjectPilotDie

src/OpenSage.Game/Logic/GameLogic.cs, src/OpenSage.Game/Logic/Player.cs
On the plus side, I don't think this breaks existing behavior and given there are definitely multiple places where we iterate over gameobjects this surely saves us _some_ cycles.
This does allow for player upgrades to be processed, which is needed for some special powers in #837 (namely capture building and radar van scan). I'm very open to other ways of accomplishing this.
=> Allow iteration of gameobjects while iterating gameobjects 🤮

src/OpenSage.Game/Logic/Object/Behaviors/SpawnBehavior.cs, src/OpenSage.Game/Logic/Object/Update/ProductionExit/SpawnPointProductionExitUpdate.cs
Honestly I should have dug a little bit deeper in #823. The issue was right there in `SpawnPointProductionExitUpdate` - everything else used model-relative coordinates, while this used world coordinates for some reason. `GetUnitCreatePoint()` is only called in two places, and both expect relative coordinates. This reverts the change in #823 that switched `TryTransformViaProductionExit()` to expecting world coordinates, as no other spawn behavior outputs that, and fixes the real underlying bug in `SpawnPointProductionExitUpdate` as mentioned above.
Tested in Generals with the GLA, and now units from supply centers, war factories, barracks, stinger sites, and tunnel networks all spawn in the correct place.
=> Fix units created at supply points spawning at wrong coords

src/OpenSage.Game.Tests/Logic/Draw/W3dModelDrawTests.cs, src/OpenSage.Game/Logic/Object/Draw/W3dModelDraw.cs
Fixes some of the bugs introduced to unit ModelConditionState and AnimationState selection in #805. This logic is getting gross and we can probably simplify it, but at the very least I've added more unit tests to ensure it doesn't get more broken.
Honestly if we just iterated over the condition states 3 times this code would probably be a lot more readable, but at any rate... This primarily fixes an issue where we would short-circuit if all of the parameters we were looking for matched, even if we didn't have an exact match. In the case of the GLA worker, if the unit had `MOVING` the first ConditionState it would find was `MOVING ATTACKING`. Since all of the unit's flags matched, it would return the mine clearing animation instead of continuing to search for an exact match (which isn't …
=> Fix some units not showing correct ModelConditionState

src/OpenSage.Game/Logic/GameLogic.cs, src/OpenSage.Game/Logic/Player.cs
This reverts commit bb67296974d883f9a35c7fbb0f303631125a5ce6, reversing changes made to a57b79ce9a01879ab5921e2a457f5539a55cd048.
I found I was getting the following exception when selling or canceling building structures. Reverting this commit seems to fix the issue. Unfortunately this means player upgrades don't get applied properly, but I guess that just means we'll have to find a different, less hacky way to iterate over those objects.
```
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
at Vortice.Direct3D11.ID3D11DeviceContext.Map(ID3D11Resource resource, Int32 subresource, MapMode mapType, MapFlags mapFlags, MappedSubresource& mappedResource)
at Vortice.Direct3D11.ID3D11DeviceContext.Map(ID3D11Resource resource, Int32 …
```
=> Revert "Merge pull request #838 from charliefoxtwo/feature/gameobject-iteration-cache"

src/OpenSage.Game/Logic/Object/Contain/OpenContain.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/SupplyAIUpdate.cs, src/OpenSage.Game/Logic/Object/Weapon/WeaponTemplate.cs, src/OpenSage.Game/Logic/OrderGenerators/Cursors.cs, src/OpenSage.Game/Logic/OrderGenerators/OrderGenerator.cs, src/OpenSage.Game/Logic/OrderGenerators/UnitOrderGenerator.cs, src/OpenSage.Mathematics/BitArray512.cs, src/OpenSage.Mathematics/BitArray`1.cs
Adds a majority of the general cursors which should apply to most games. I'm not yet sure where unit special power cursors will fit in to this model (which do appear even if the special power hasn't been explicitly selected, like for capturing a neutral building or for black lotus doing just about anything), but that's a problem for future charlie.
=> Add more cursors and orders to UnitOrderGenerator

src/OpenSage.Game/Logic/Object/Contain/GarrisonContain.cs, src/OpenSage.Game/Logic/Object/Contain/HealContain.cs, src/OpenSage.Game/Logic/Object/Contain/OpenContain.cs, src/OpenSage.Game/Logic/Object/Contain/OverlordContain.cs, src/OpenSage.Game/Logic/Object/Contain/TransportContain.cs, src/OpenSage.Game/Logic/Object/Contain/TunnelContain.cs
It seems original owner is tracked via team, and as we aren't currently setting teams for players this behavior is currently worked by returning the object to plyrcivilian
Fixes #814
=> Change object owner when garrisoned

src/OpenSage.Launcher/Program.cs
Allows for Zero Hour to be launched specifying both its own install path as well as the Generals install path (previously, launching Zero Hour with a specified install path would fail to start as no base game would be found).
=> Allow launching parent game with base game from custom paths

src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/ObjectDefinition.cs, src/OpenSage.Game/Terrain/HeightMap.cs, src/OpenSage.Game/Terrain/Terrain.cs
Generals will lower any terrain around an object higher than the centerpoint of the object being placed. It will not raise terrain that is lower than the centerpoint. Adding support for that could be a nice improvement in the future, but would require adjusting things like roads as well.
Roads in Generals currently always render behind structures, regardless of elevation. This is not the case in OpenSAGE, so that still looks a bit wonky currently.
This also removes any scenery (such as shrubbery, rubble, signposts, etc) from the build area.
Generals:
OpenSAGE:
Here's an example of where one might build a barracks, with the terrain around it being adjusted (circled red for clarity):
Here's a more contrived example as we don't currently check that the terrain variation is within allowable …
=> Adjust uneven terrain around objects being built

src/OpenSage.Game/Gui/ControlBar/CommandButton.cs, src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs, src/OpenSage.Mods.Generals/Gui/GeneralsExpPointsCallbacks.cs
These are either sciences granted via other means (like the MOAB upgrade) or buttons used by the AI (like building the various GLA combat cycle variants)
=> Hide SCRIPT_ONLY command buttons

src/OpenSage.Game/Logic/OrderGenerators/ConstructBuildingOrderGenerator.cs
The unit already moves via the state machine order given when their build target is set. A manual move command is unnecessary and plays the VoiceMove audio queue, which we don't want in this case.
=> Remove unnecessary move order when constructing building

src/OpenSage.Game/Logic/Object/Collide/MoneyCrateCollide.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Update/AutoDepositUpdate.cs
This ties the next deposit frame to a persisted field, and implements a few more of the moduledata properties. I'm still not sure what that second persisted bool is for... it was always `true` in my testing.
=> Implement AutoDepositUpdate persistence and generals/zh moduledata

src/OpenSage.Game/GameData.cs, src/OpenSage.Game/Logic/AI/AIStates/HackInternetState.cs, src/OpenSage.Game/Logic/AI/AIStates/StartHackingInternetState.cs, src/OpenSage.Game/Logic/AI/AIStates/StopHackingInternetState.cs, src/OpenSage.Game/Logic/Object/BehaviorModule.cs, src/OpenSage.Game/Logic/Object/Behaviors/AutoHealBehavior.cs, src/OpenSage.Game/Logic/Object/Behaviors/PropagandaTowerBehavior.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/SpecialPower.cs, src/OpenSage.Game/Logic/Object/SpecialPower/SpecialPower.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/HackInternetAIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/BaseRegenerateUpdate.cs, src/OpenSage.Game/Logic/Object/Update/BattlePlanUpdate.cs, src/OpenSage.Game/Logic/Object/Update/HordeUpdate.cs, src/OpenSage.Game/Logic/Object/Update/RebuildHoleUpdate.cs, src/OpenSage.Game/Logic/Object/Update/StealthDetectorUpdate.cs, src/OpenSage.Game/Logic/Object/Update/UpdateModule.cs, src/OpenSage.Game/Logic/Player.cs, src/OpenSage.Game/StatePersister.cs
I've touched quite a few modules recently, and yet only even more recently discovered we had methods for parsing time as `LogicFrameSpan`s, and imo it makes a lot more sense to do things that way. This updates most of those modules to operate with `LogicFrameSpan`s instead.
Disclaimer - I haven't gone through and tested every module to verify it works. A quick smoke test of repairing and healing seems to indicate it works though.
=> Parse time in ModuleData objects as LogicFrameSpans

src/OpenSage.Game/Data/InstallationLocator.cs
I was playing around with getting zero hour sav parsing to work, and was encountering issues that made it clear OpenSAGE wasn't respecting the environment variable paths for the game installs I had set. I dug into this, and it looks like we prioritized registry key installs over environment variable installs. To me, this seems backwards - if the environment variables are set, they should be considered an override of the registry paths. This moves the environment variable paths up to be considered before the registry key paths. It also fixes the base game not being loaded when using an environment variable path.
=> Make env var paths take precedence over registry paths

src/OpenSage.Game/Client/Drawable.cs, src/OpenSage.Game/Logic/Object/Draw/W3dModelDraw.cs, src/OpenSage.Game/ModuleBase.cs
Particle systems now no longer remain after the DrawModule (or Drawable) gets disposed
closes #686
=> Fix W3dModelDraw not disposing its particle systems correctly

src/OpenSage.Game/Data/Utilities/Extensions/PixelFormatExtensions.cs, src/OpenSage.Game/Gui/Wnd/Images/MappedImageUtility.cs, src/OpenSage.Mathematics/MathUtility.cs
=> Fixed MappedImageUtility::CreateTexture to handle block compression properly

src/OpenSage.Game/Gui/Wnd/Controls/Label.cs
=> Fixed UI Labels ignoring border color

src/OpenSage.Game/Logic/Player.cs
=> Deselect previous units when non-additively selecting new unit

src/OpenSage.Benchmarks.DataStructures/BenchQuadtreeItem.cs, src/OpenSage.Game.Tests/DataStructures/QuadtreeTests.cs, src/OpenSage.Game/DataStructures/ICollidable.cs, src/OpenSage.Game/DataStructures/IQuadtree.cs, src/OpenSage.Game/DataStructures/Quadtree.cs, src/OpenSage.Game/DataStructures/QuadtreeNode.cs, src/OpenSage.Game/GameContext.cs, src/OpenSage.Game/Scene3D.cs
Supersedes #925 (ported over tests)
After benchmark testing with [Orthogonal Arrays](https://en.wikipedia.org/wiki/Orthogonal_array), the minimum node geometric size and max items per node parameters were tweaked for better performance.
Additionally, an overlap parameter was added. This scales the subgrids by the provided factor, such that each subgrid overlaps its neighbors. This helps prevent hotspots on cell borders from piling up in the parent nodes.
This new implementation persists the existing behavior that two entities whose borders perfectly touch are **not** considered colliding. If that is not the desired behavior we may wish to address that separately.
This also switches to using an interface in the method signatures instead of the class name itself, partially because that made …
=> Replace Quadtree with more accurate implementation

src/OpenSage.Game/Logic/Player.cs
Note the house colors on the oil derrick, the cash text, and the radar spots on the minimap change in the before/after.
=> Fix Neutral house colors

src/OpenSage.Game/Logic/Object/Body/ActiveBody.cs, src/OpenSage.Game/Logic/Object/GameObject.cs
Noticed then when I was doing #931 
Note the red health bar going left temporarily.
=> Fix health able to go below zero

src/OpenSage.Game/Data/Ini/IniParser.cs
Fixes #825
auto repair on USA structures is now much slower, as expected
=> Fix Percentages with decimals being parsed incorrectly

src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/ObjectCreationList.cs, src/OpenSage.Game/Logic/Object/Update/LifetimeUpdate.cs
Unit and rubble persist indefinitely.
Unit and rubble sink and are deleted according to `LifetimeUpdate` and `SlowDeathBehavior`
=> Fix units not sinking/disappearing after death

src/OpenSage.Game/Logic/Object/Behaviors/SpawnBehavior.cs, src/OpenSage.Game/Logic/Object/Die/UpgradeDie.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Update/SlavedUpdate.cs, src/OpenSage.Game/Logic/Object/Upgrade/ObjectCreationUpgrade.cs
UpgradeDie is now properly implemented (though removing applied upgrades isn't yet supported - we'll still have to figure out how we want to tackle that one), and additional parts of SlavedUpdate are now persisted (though the module still needs to be fixed up to be fully compatible with generals saves).
The upgrade is no longer considered purchased (though is still disabled as it's considered triggered), and the spy drone upgrade is now purchasable.
When the parent dies, the child dies too.
=> Update slaved module capabilities

src/OpenSage.Game/Logic/AI/AIStateMachine.cs, src/OpenSage.Game/Logic/AI/AIStates/AttackAreaState.cs, src/OpenSage.Game/Logic/AI/AIStates/AttackMoveState.cs, src/OpenSage.Game/Logic/AI/AIStates/HackInternetState.cs, src/OpenSage.Game/Logic/AI/AIStates/IdleState.cs, src/OpenSage.Game/Logic/AI/AIStates/StartHackingInternetState.cs, src/OpenSage.Game/Logic/AI/AIStates/StopHackingInternetState.cs, src/OpenSage.Game/Logic/AI/State.cs, src/OpenSage.Game/Logic/AI/StateMachineBase.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/AIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/HackInternetAIUpdate.cs
As a prerequisite to #879, I wanted to make `State` subclasses contain not just data, but also behavior. 
We've done this already with our [WeaponStateMachine](https://github.com/OpenSAGE/OpenSAGE/blob/master/src/OpenSage.Game/Logic/Object/Weapon/WeaponStates/WeaponStateMachine.cs), and it's pretty standard in any case. See [Super Simple State Machine](https://keithmaggio.wordpress.com/code/supersimplestatemachine/) for another example. 
Having `State` subclasses contain behavior and handle transitions to the next state should provide a nice framework for implementing more of these.
=> Move hacking behavior to state classes

src/OpenSage.Game/Logic/Object/ObjectDefinition.cs, src/OpenSage.Game/Logic/Orders/OrderProcessor.cs
Previously this assumed that the default was null, but the default is actually 0
=> Award cash on building sell

src/OpenSage.Game/Logic/Object/Behaviors/ParkingPlaceBehavior.cs, src/OpenSage.Game/Logic/Object/Contain/OpenContain.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Update/ProductionExit/DefaultProductionExitUpdate.cs, src/OpenSage.Game/Logic/Object/Update/ProductionExit/QueueProductionExitUpdate.cs, src/OpenSage.Game/Logic/Object/Update/ProductionExit/SupplyCenterProductionExitUpdate.cs, src/OpenSage.Game/Logic/Object/Update/RallyPoint/IHasRallyPoint.cs, src/OpenSage.Game/Logic/Object/Update/RallyPoint/RallyPointManager.cs
There may be other behaviors which persist rally points, but these are the ones I was able to find. Initially I thought about just having `IProductionExit` implement `IHasRallyPoint`, but `SpawnPointProductionExitUpdate` also implements `IProductionExit` and a cursory investigation doesn't reveal any obvious place that it would store the rally point.
=> Persist rally points

src/OpenSage.Game/Logic/Object/BehaviorModule.cs, src/OpenSage.Game/Logic/Object/Production/ProductionJob.cs, src/OpenSage.Game/Logic/Object/Update/ProductionExit/IProductionExit.cs, src/OpenSage.Game/Logic/Object/Update/ProductionExit/QueueProductionExitUpdate.cs, src/OpenSage.Game/Logic/Object/Update/ProductionUpdate.cs
Includes a fairly sizeable refactor of ProductionUpdate and ProductionJob as well, updating the classes so most of the core state information is persisted.
Fixes #948
Some of the BFME stuff has been commented out as it no longer fits the proper implementation. We'll also still need to investigate scaling production times (for example, USA/China low power or GLA with power)
=> Implement QueueProductionExitUpdate

src/OpenSage.Game.Tests/Logic/Object/BehaviorModuleTest.cs, src/OpenSage.Game.Tests/Logic/Object/Behaviors/OverchargeBehaviorTests.cs, src/OpenSage.Game.Tests/Logic/Object/ModuleTest.cs, src/OpenSage.Game.Tests/Logic/Object/Update/UpdateModuleTest.cs, src/OpenSage.Game.Tests/StatePersisterTest.cs, src/OpenSage.Game/Data/Sav/SaveFile.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/IGame.cs, src/OpenSage.Game/Logic/Object/Behaviors/OverchargeBehavior.cs, src/OpenSage.Game/Network/SkirmishGameSettings.cs, src/OpenSage.Game/Network/SkirmishManager.cs, src/OpenSage.Game/StatePersister.cs, src/OpenSage.Tools.Sav2Json/JsonSaveWriter.cs
`IGame` is the bare minimum interface required and does not extract _all_ behavior from `Game`. I also have not gone through to replace other usages of `Game` with `IGame` where not required for the persister.
++++++++++++++++++
(my cat typed that line ^. I felt it important to leave in.)
I added basic tests for OverchargeBehavior parsing as a proof of concept, since it's very simple. This framework should be easy enough to expand to other behaviors (or even things that aren't behaviors). In some places when parsing we rely on the various properties of `IGame` being implemented, but I think we can cross those bridges as we come to them.
=> Enable persistence unit testing

src/OpenSage.Game/StatePersister.cs
I've found myself using this function a _lot_ when testing. Maybe someone can point me to a better way, but my workflow has been:
- create a sav file with the behavior I'm interested in introspecting
- replace the `Load` function of the behavior with `LogToSegmentEnd()`
- run Sav2Json
If this would benefit others, I'd like to commit this that way I don't have to keep stashing and popping it 😆 
Output might look something like this. It's also easy to copy/paste something like this into HexEd.it for further processing.
```
[22:23:22.3900][Trace] Skirmish game status is now Started
[22:23:22.4205][Info] Set active condition state for AmericaVehicleDozer
01 00 00 00 00 00 00 00 00 00 00 
[22:23:22.4424][Info] Weapon DozerMineDisarmingWeapon on game object  transitioning to state Inactive …
```
=> Add debug function to persister to log segment bytes

src/OpenSage.Game.Tests/Logic/Object/Behaviors/GenerateMinefieldBehaviorTests.cs, src/OpenSage.Game.Tests/StatePersisterTest.cs, src/OpenSage.Game/Logic/Object/Behaviors/GenerateMinefieldBehavior.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/OrderGenerators/UnitOrderGenerator.cs, src/OpenSage.Game/StatePersister.cs, src/OpenSage.Game/Terrain/Terrain.cs
This still doesn't handle certain things such as generating rectangular minefields or the ability to upgrade minefields.
#968
Demonstrating different packing depending on the unit type:
=> Add initial implementation of GenerateMinefieldBehavior

src/OpenSage.Game/Data/Map/SidesListUtility.cs, src/OpenSage.Game/Logic/AI/AIPlayer.cs, src/OpenSage.Game/Logic/AI/AIStates/MoveTowardsState.cs, src/OpenSage.Game/Logic/Object/Behaviors/PhysicsBehavior.cs, src/OpenSage.Game/Logic/Object/Contain/OpenContain.cs, src/OpenSage.Game/Logic/Object/Locomotor.cs, src/OpenSage.Game/Logic/Object/ObjectCreationList.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/AIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/DozerAndWorkerState.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/TransportAIUpdate.cs, src/OpenSage.Game/Scripting/ScriptingSystem.cs, src/OpenSage.Game/StatePersister.cs
This PR has a few tweaks for parsing `.sav` files, including giving names to a few more fields related to pathing and physics. I used a test map with a single Humvee, and a script that moved that Humvee only in the X direction, to work this out.
=> Improve .sav file parsing

src/OpenSage.Game/Logic/CrateData.cs, src/OpenSage.Game/Logic/Object/BehaviorModule.cs, src/OpenSage.Game/Logic/Object/Die/CreateCrateDie.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Update/DeletionUpdate.cs
Fixes #975
Creating a crate would normally be disabled with a null killer, but I've disabled that check for these tests. Additionally, the crate normally wouldn't be visible for a non-GLA player, but that hasn't been implemented yet.
Changes also needed to be made to run DeletionUpdate for "dead" objects, so that crates are deleted per their behavior definition.
=> Implement CreateCrateDie

src/OpenSage.Game/Client/Drawable.cs, src/OpenSage.Game/Client/GameClient.cs, src/OpenSage.Game/Entity.cs, src/OpenSage.Game/Logic/GameLogic.cs, src/OpenSage.Game/Logic/Object/Draw/W3dModelDraw.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/OrderGeneratorSystem.cs, src/OpenSage.Game/Logic/OrderGenerators/RallyPointOrderGenerator.cs, src/OpenSage.Game/Logic/SelectionSystem.cs
This fixes #970. I found there were two causes of that crash:
1. The game object created for the rally point marker wasn't registered correctly with `GameClient`, so when it was disposed it had an unrecognized ID.
2. When a .sav is loaded, lists of existing game objects and drawables are cleared, but they're not disposed. When they get disposed later on they can cause a crash.
This PR fixes both of those. In the process I added the ability for `Drawable` to exist as a standalone thing, because I'm pretty sure that's how `RallyPointMarker` is supposed to be used.
=> Move rally point marker drawing to order generator

src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/StatePersister.cs
Also fixes a bug in PersistBitArrayAsUInt32 if the enum had less than 32 items
=> Convert GameObject weaponBonusTypes to BitArray

src/OpenSage.Game.Tests/Logic/Object/Behaviors/PhysicsBehaviorTests.cs, src/OpenSage.Game.Tests/Logic/Object/Update/UpdateModuleTest.cs, src/OpenSage.Game/Logic/Object/BehaviorModule.cs, src/OpenSage.Game/Logic/Object/Behaviors/AutoHealBehavior.cs, src/OpenSage.Game/Logic/Object/Behaviors/BuildingBehavior.cs, src/OpenSage.Game/Logic/Object/Behaviors/CastleBehavior.cs, src/OpenSage.Game/Logic/Object/Behaviors/GateOpenAndCloseBehavior.cs, src/OpenSage.Game/Logic/Object/Behaviors/OverchargeBehavior.cs, src/OpenSage.Game/Logic/Object/Behaviors/PhysicsBehavior.cs, src/OpenSage.Game/Logic/Object/Behaviors/SpawnBehavior.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Helpers/ObjectFiringTrackerHelper.cs, src/OpenSage.Game/Logic/Object/Helpers/ObjectWeaponStatusHelper.cs, src/OpenSage.Game/Logic/Object/SpecialPower/CashHackSpecialPower.cs, src/OpenSage.Game/Logic/Object/SpecialPower/OCLSpecialPower.cs, src/OpenSage.Game/Logic/Object/SpecialPower/SpecialPower.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/AIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/FoundationAIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AutoFindHealingUpdate.cs, src/OpenSage.Game/Logic/Object/Update/BaseRegenerateUpdate.cs, src/OpenSage.Game/Logic/Object/Update/DeletionUpdate.cs, src/OpenSage.Game/Logic/Object/Update/UpdateModule.cs, src/OpenSage.Mathematics/BitArray`1.cs, src/OpenSage.Tools.Sav2Json/JsonSaveWriter.cs
Small refactoring of `UpdateModule` based on parsing `UpdateFrame.Something` as probably meaning the execution order that update modules are updated. This value is always constant for a given module type. It is always either 0, 1, 2, or 3. Almost all module types are 2. Some examples:
- AIUpdate and its subclasses: 0
- PhysicsBehavior: 1
- _every other update module that I've seen_: 2
- ObjectWeaponStatusHelper: 3
- ObjectFiringTrackerHelper: 3
The order makes some sense - `AIUpdate` does the majority of stuff, including applying physics forces etc. Then `PhysicsBehavior` updates object's position and angle. Then all the other `UpdateModule`s do their thing (although this would imply that any physics forces applied by these update modules don't get applied till the next frame, which would …
=> Rename UpdateFrame.Something to UpdateOrder

LICENSE-EA.md
We plan to port some of EA's recently released [Cnc_Generals_Zero_Hour](https://github.com/electronicarts/CnC_Generals_Zero_Hour)  C++ code to C# code in OpenSAGE.
EA's code is licensed under GPL V3.
OpenSAGE has historically been licensed under LGPL V3.
In order to port EA's code, we need to re-license OpenSAGE from LGPL V3 to GPL V3. This is permitted by the terms of the LGPL V3 - [see here](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility) for more details.
=> Re-license from LGPL V3 to GPL V3

.vscode/launch.json
Regression from #724 
Configurations in VS Code's `launch.json` still referenced versions built with `net6.0`. If you have an old OpenSAGE folder it might run some years old version, and otherwise it just didn't work.
=> Fix VS Code launch configurations

.vscode/launch.json, src/OpenSage.FileFormats/BinaryReaderExtensions.cs, src/OpenSage.FileFormats/BinaryWriterExtensions.cs, src/OpenSage.Game/Data/Map/HeightMapData.cs, src/OpenSage.Game/Data/Map/PolygonTrigger.cs, src/OpenSage.Game/Data/Map/PolygonTriggers.cs, src/OpenSage.Game/Logic/GameLogic.cs, src/OpenSage.Game/Terrain/HeightMap.cs, src/OpenSage.Game/Terrain/Terrain.cs, src/OpenSage.Game/Terrain/WaterAreaCollection.cs, src/OpenSage.Mathematics/Point3D.cs
Resolves #1038
- Simplify and reformat BinaryReaderExtensions
- Improve null handling & reformat BinaryWriterExtensions
- Add VS Code launch configuration for Tournament Island
- Alpine Assault and Generals' shell map don't have any water 
- Update PolygonTrigger & related code based on Generals OSS release
- https://github.com/electronicarts/CnC_Generals_Zero_Hour/blob/0a05454d8574207440a5fb15241b98ad0b435590/GeneralsMD/Code/GameEngine/Source/GameLogic/Map/PolygonTrigger.cpp 
Almost everything was ported from `PolygonTrigger.cpp`, exceptions:
- Methods that mutate the polygon trigger were not implemented, because in the original they only exist for World Builder.
- `getWaterHandle` was not implemented, because the vast majority of functionality related to it is in `TerrainLogic.cpp`. …
=> Port PolygonTrigger from Generals OSS release

src/OpenSage.Game/Data/Map/AssetProperty.cs, src/OpenSage.Game/Data/Map/AssetPropertyCollection.cs, src/OpenSage.Game/Data/Map/Player.cs, src/OpenSage.Game/Data/Map/SidesList.cs, src/OpenSage.Game/Data/Map/SidesListUtility.cs, src/OpenSage.Game/Data/Map/Team.cs, src/OpenSage.Game/Data/Map/WaypointPath.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Player.cs, src/OpenSage.Game/Logic/PlayerManager.cs, src/OpenSage.Game/Logic/TeamFactory.cs, src/OpenSage.Game/Scripting/Waypoints.cs, src/OpenSage.Mathematics/ColorRgb.cs
* Refactor Data.Map.Player and Data.Map.Team to expose properties instead of a dynamically typed collection
* Using a dynamically typed dictionary is _technically_ closer to how SAGE actually works, but it's also really messy, a bit slow and hard to document. 
* The properties were created based on the list of `Team` and `Player` keys in [`WellKnownKeys.h`](https://github.com/electronicarts/CnC_Generals_Zero_Hour/blob/0a05454d8574207440a5fb15241b98ad0b435590/GeneralsMD/Code/GameEngine/Include/Common/WellKnownKeys.h)
* `AssetPropertyType.Integer` is now treated as a signed integer, matching Generals / ZH implementation. Our implementation used to use uint, and there were a few places outside of player & team code where an integer property is incorrectly cast from boxed integer to boxed …
=> Refactor Data.Map.Player and Data.Map.Team

src/OpenSage.Game/Client/Drawable.cs, src/OpenSage.Game/Logic/Object/AnimationState.cs, src/OpenSage.Game/Logic/Object/ArmorTemplateSet.cs, src/OpenSage.Game/Logic/Object/Body/ActiveBody.cs, src/OpenSage.Game/Logic/Object/Body/BodyModule.cs, src/OpenSage.Game/Logic/Object/Body/InactiveBody.cs, src/OpenSage.Game/Logic/Object/Draw/DrawModule.cs, src/OpenSage.Game/Logic/Object/Draw/W3dModelDraw.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/IConditionState.cs, src/OpenSage.Game/Logic/Object/ModelConditionState.cs, src/OpenSage.Game/Logic/Object/ObjectDefinition.cs, src/OpenSage.Game/Logic/Object/Update/HordeUpdate.cs, src/OpenSage.Game/Logic/Object/Upgrade/ArmorUpgrade.cs, src/OpenSage.Game/Logic/Object/Upgrade/UpgradeModule.cs, src/OpenSage.Game/Utilities/BitArrayMatchFinder.cs
Resolves #1247.
* Extract `BitArrayMatchFinder` out of `W3dModelDraw` - this is used for armor sets as well as model condition states
* Store current armor in `ActiveBody`, not `GameObject`
* Add some upgrade and terrain decal stuff that got dragged in, even though that part of `ArmorUpgrade` seems like a huge hack (hopefully we can improve that later on)
=> Port ArmorUpgrade from Generals OSS release

src/OpenSage.Game/Data/Map/BuildList.cs, src/OpenSage.Game/Data/Map/MapFile.cs, src/OpenSage.Game/Data/Map/Player.cs, src/OpenSage.Game/Data/Map/PolygonTriggers.cs, src/OpenSage.Game/Game.cs, src/OpenSage.Game/Logic/AI/AIData.cs, src/OpenSage.Game/Logic/GameLogic.cs, src/OpenSage.Game/Logic/Map/BuildListInfo.cs, src/OpenSage.Game/Logic/Map/PolygonTrigger.cs, src/OpenSage.Game/Logic/Map/SidesList.cs, src/OpenSage.Game/Logic/Map/SidesListUtility.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Player.cs, src/OpenSage.Game/Terrain/WaterArea.cs
Move these to `OpenSage.Logic.Map` to match the structure of the C++ code more closely (as mentioned in #1295).
=> Move SidesList, BuildListInfo and PolygonTrigger to OpenSage.Logic.Map

.github/workflows/ci.yml, .github/workflows/format.yml
This will allow us to have the formatting checks display separately from the build, so the builds can still run independently of any formatting issues.
=> Split formatting check into separate workflow

src/OpenSage.Game/Content/ContentManager.cs, src/OpenSage.Game/Content/Translation/ITranslationManager.cs, src/OpenSage.Game/Content/Translation/Providers/StrTranslationProvider.cs, src/OpenSage.Game/Content/Translation/TranslationManager.cs, src/OpenSage.Game/Data/Wnd/Parser/WndParser.cs, src/OpenSage.IO/BigFileSystem.cs, src/OpenSage.IO/SkudefReader.cs
- Fix `WndParser` crashing with ZH Steam version's `MainMenu.wnd`
- The Steam version of base Generals doesn't have the same issue - looks like the Wnd file was modified by hand, and the ZH version has a small syntax issue which the game seems to handle without issues, but OpenSAGE didn't like it.
- Change .big file handling to override existing entries in case of duplicate filename
- This is potentially a pretty big change, but it seems to match the original engine. I don't think `Patch` .big files could work any other way.
- Without this change the actual load order was kind of inverted (vs how it is other games) - the files that were loaded first won, and there was no way to override their entries afterwards.
- Update .big file load order logic to match ZH Steam version
- This is …
=> Steam version fixes

.git-blame-ignore-revs, .vscode/settings.json
Based on instructions from https://www.stefanjudis.com/today-i-learned/how-to-exclude-commits-from-git-blame/
- Add `.git-blame-ignore-revs` file to make `git blame` more usable after #1298
- After we switched to file-scoped namespaces, almost every line in every file was pointing to that commit.
- [GitHub recognizes this file and automatically uses it for blame](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-and-understanding-files#ignore-commits-in-the-blame-view)
- However, git doesn't use this file automatically and from what I've gathered there's no way to configure it to be enabled by default. You might need to explicitly enable the file with `git config blame.ignoreRevsFile .git-blame-ignore-revs`
- Add workspace VS Code config to use …
=> Ignore changes from reformat PR in git blame

src/OpenSage.Game/Logic/AI/AIStates/HackInternetAIUpdate/HackInternetState.cs, src/OpenSage.Game/Logic/CrateData.cs, src/OpenSage.Game/Logic/Object/Create/ExperienceLevelCreate.cs, src/OpenSage.Game/Logic/Object/Create/VeterancyGainCreate.cs, src/OpenSage.Game/Logic/Object/Die/CreateCrateDie.cs, src/OpenSage.Game/Logic/Object/ExperienceTracker.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Update/AutoDepositUpdate.cs, src/OpenSage.Game/Logic/Object/Update/ExperienceUpdate.cs, src/OpenSage.Game/Logic/Object/Update/ProductionUpdate.cs, src/OpenSage.Game/Logic/Object/Upgrade/ExperienceScalarUpgrade.cs, src/OpenSage.Game/Logic/Object/VeterancyLevel.cs, src/OpenSage.Game/Logic/Object/VeterancyValues.cs, src/OpenSage.Game/Logic/Player.cs, src/OpenSage.Game/Logic/Team.cs, src/OpenSage.Game/Scene25D.cs, src/OpenSage.Mods.Generals/GeneralsScene25D.cs, src/OpenSage.Mods.Generals/Gui/GeneralsControlBar.cs
Resolves #1268.
Replaces `VeterancyHelper` with `ExperienceTracker`, ported from the [original C++ class](https://github.com/electronicarts/CnC_Generals_Zero_Hour/blob/main/GeneralsMD/Code/GameEngine/Source/GameLogic/Object/ExperienceTracker.cpp). Also includes some other related code I had to port, such as player / team relationship logic.
=> Port ExperienceTracker & related code

src/OpenSage.Game/Logic/AcademyStats.cs, src/OpenSage.Game/Logic/BankAccount.cs, src/OpenSage.Game/Logic/Object/BehaviorModule.cs, src/OpenSage.Game/Logic/Player.cs
- Update `BankAccount` with ported code from Money.cpp
- `BankAccount` is the name of our original implementation. I tried renaming it `Money` to match Generals, but since it has a field named `Money` (both in our version and in Generals), the compiler didn't allow it. I think our current name is better anyway.
- Add partial port of `AcademyStats` (which is used to generate end-of-game strategy tips that are shown in ZH's score screen)
- This is a pretty long class and IMHO not very important in the grand scheme of things. I added all of the fields as it was a pretty simple mechanical process, and the method used by `BankAccount`.
- I also implemented `Persist`. After finishing the implementation I noticed that ZH doesn't seem to ever call the `xfer` method, so even though there's a …
=> Port Money.cpp / BankAccount and (some of) AcademyStats.cpp

src/OpenSage.Game/Diagnostics/MainView.cs, src/OpenSage.Game/Diagnostics/UpdateModulesView.cs, src/OpenSage.Game/Logic/GameLogic.cs, src/OpenSage.Game/Logic/Object/BehaviorModule.cs, src/OpenSage.Game/Logic/Object/Behaviors/AutoHealBehavior.cs, src/OpenSage.Game/Logic/Object/Behaviors/OverchargeBehavior.cs, src/OpenSage.Game/Logic/Object/Behaviors/PhysicsBehavior.cs, src/OpenSage.Game/Logic/Object/Behaviors/SpawnBehavior.cs, src/OpenSage.Game/Logic/Object/GameObject.cs, src/OpenSage.Game/Logic/Object/Update/UpdateModule.cs, src/OpenSage.Tools.Sav2Json/JsonSaveWriter.cs
This is a port of the "sleepy update" logic from `GameLogic.cpp`. It's the code that:
- keeps track of all `UpdateModule`s in the game
- sorts them according to the next frame (and phase within that frame) that they want to be called
- calls update modules at the appropriate time
I've also added a diagnostic view to Developer Mode for this.
Note that `SleepyUpdateList` is _very_ similar to .NET's built-in `PriorityQueue<T>`. I didn't use that built-in class because this custom one is slightly faster during updates, because it stores each update module's index within the list within each update module.
=> Implement sleepy updates

src/OpenSage.Game/Logic/AI/AIStates/AIState32.cs, src/OpenSage.Game/Logic/AI/AIStates/AttackAreaState.cs, src/OpenSage.Game/Logic/AI/AIStates/AttackMoveState.cs, src/OpenSage.Game/Logic/AI/AIStates/AttackState.cs, src/OpenSage.Game/Logic/AI/AIStates/ChinookAIUpdate/ChinookCombatDropState.cs, src/OpenSage.Game/Logic/AI/AIStates/DockState.cs, src/OpenSage.Game/Logic/AI/AIStates/GuardInTunnelNetworkState.cs, src/OpenSage.Game/Logic/AI/AIStates/GuardState.cs, src/OpenSage.Game/Logic/AI/AIStates/HackInternetAIUpdate/HackInternetState.cs, src/OpenSage.Game/Logic/AI/AIStates/HackInternetAIUpdate/StartHackingInternetState.cs, src/OpenSage.Game/Logic/AI/AIStates/HackInternetAIUpdate/StopHackingInternetState.cs, src/OpenSage.Game/Logic/AI/AIStates/IdleState.cs, src/OpenSage.Game/Logic/AI/AIStates/JetAIUpdate/WaitForAirfieldWinchesterState.cs, src/OpenSage.Game/Logic/AI/AIUpdateStateMachine.cs, src/OpenSage.Game/Logic/AI/State.cs, src/OpenSage.Game/Logic/AI/StateMachineBase.cs, src/OpenSage.Game/Logic/AI/SupplyAIUpdateStateMachine.cs, src/OpenSage.Game/Logic/Object/BehaviorModule.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/AIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/ChinookAIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/DozerAndWorkerState.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/HackInternetAIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/JetAIUpdate.cs, src/OpenSage.Game/Logic/Object/Update/AIUpdate/WorkerAIUpdate.cs, src/OpenSage.Game/StatePersister.cs
This PR does some foundational refactoring of our state machine code, in preparation for porting some actual state classes. We were fairly close with our existing implementation. I've changed how states are configured to match the original, including specifying a "next" state, for both "success" and "failure" conditions.
I went through a few iterations on this, to see if there was a more elegant way to write this code. But because state classes (in particular the idle state) can be used in multiple different state machines, potentially with different IDs, it is necessary to have state IDs defined completely separately from the state classes they're associated with. So a direct port seemed like the best option.
=> Port some state machine code
